CREATE TABLE Genre (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name VARCHAR(255) NOT NULL UNIQUE,
  listened_time SMALLINT DEFAULT 0
);

CREATE TABLE RefreshToken (token VARCHAR(255));

-- Thanks to https://gist.github.com/andytlr/4104c667a62d8145aa3a for most of the list
INSERT INTO Genre (name) VALUES ("A Cappella");
INSERT INTO Genre (name) VALUES ("Abstract");
INSERT INTO Genre (name) VALUES ("Abstract Beats");
INSERT INTO Genre (name) VALUES ("Abstract Hip Hop");
INSERT INTO Genre (name) VALUES ("Abstract Idm");
INSERT INTO Genre (name) VALUES ("Abstractro");
INSERT INTO Genre (name) VALUES ("Accordion");
INSERT INTO Genre (name) VALUES ("Acid House");
INSERT INTO Genre (name) VALUES ("Acid Jazz");
INSERT INTO Genre (name) VALUES ("Acid Techno");
INSERT INTO Genre (name) VALUES ("Acousmatic");
INSERT INTO Genre (name) VALUES ("Acoustic Blues");
INSERT INTO Genre (name) VALUES ("Acoustic Pop");
INSERT INTO Genre (name) VALUES ("Adult Standards");
INSERT INTO Genre (name) VALUES ("African Percussion");
INSERT INTO Genre (name) VALUES ("African Rock");
INSERT INTO Genre (name) VALUES ("Afrikaans");
INSERT INTO Genre (name) VALUES ("Afrobeat");
INSERT INTO Genre (name) VALUES ("Afrobeats");
INSERT INTO Genre (name) VALUES ("Aggrotech");
INSERT INTO Genre (name) VALUES ("Albanian Pop");
INSERT INTO Genre (name) VALUES ("Album Rock");
INSERT INTO Genre (name) VALUES ("Albuquerque Indie");
INSERT INTO Genre (name) VALUES ("Alternative Americana");
INSERT INTO Genre (name) VALUES ("Alternative Country");
INSERT INTO Genre (name) VALUES ("Alternative Dance");
INSERT INTO Genre (name) VALUES ("Alternative Emo");
INSERT INTO Genre (name) VALUES ("Alternative Hardcore");
INSERT INTO Genre (name) VALUES ("Alternative Hip Hop");
INSERT INTO Genre (name) VALUES ("Alternative Metal");
INSERT INTO Genre (name) VALUES ("Alternative Metalcore");
INSERT INTO Genre (name) VALUES ("Alternative New Age");
INSERT INTO Genre (name) VALUES ("Alternative Pop");
INSERT INTO Genre (name) VALUES ("Alternative Pop Rock");
INSERT INTO Genre (name) VALUES ("Alternative R&b");
INSERT INTO Genre (name) VALUES ("Alternative Rock");
INSERT INTO Genre (name) VALUES ("Alternative Roots Rock");
INSERT INTO Genre (name) VALUES ("Ambeat");
INSERT INTO Genre (name) VALUES ("Ambient");
INSERT INTO Genre (name) VALUES ("Ambient Dub Techno");
INSERT INTO Genre (name) VALUES ("Ambient Fusion");
INSERT INTO Genre (name) VALUES ("Ambient Idm");
INSERT INTO Genre (name) VALUES ("Ambient Psychill");
INSERT INTO Genre (name) VALUES ("Ambient Trance");
INSERT INTO Genre (name) VALUES ("Anarcho-punk");
INSERT INTO Genre (name) VALUES ("Andean");
INSERT INTO Genre (name) VALUES ("Anime");
INSERT INTO Genre (name) VALUES ("Anime Score");
INSERT INTO Genre (name) VALUES ("Anti-folk");
INSERT INTO Genre (name) VALUES ("Antiviral Pop");
INSERT INTO Genre (name) VALUES ("Appalachian Folk");
INSERT INTO Genre (name) VALUES ("Arab Folk");
INSERT INTO Genre (name) VALUES ("Arab Pop");
INSERT INTO Genre (name) VALUES ("Arabesk");
INSERT INTO Genre (name) VALUES ("Argentine Indie");
INSERT INTO Genre (name) VALUES ("Argentine Reggae");
INSERT INTO Genre (name) VALUES ("Argentine Rock");
INSERT INTO Genre (name) VALUES ("Armenian Folk");
INSERT INTO Genre (name) VALUES ("Art Rock");
INSERT INTO Genre (name) VALUES ("Athens Indie");
INSERT INTO Genre (name) VALUES ("Atmospheric Black Metal");
INSERT INTO Genre (name) VALUES ("Atmospheric Post Rock");
INSERT INTO Genre (name) VALUES ("Atmospheric Post-metal");
INSERT INTO Genre (name) VALUES ("Aussietronica");
INSERT INTO Genre (name) VALUES ("Austindie");
INSERT INTO Genre (name) VALUES ("Australian Alternative Rock");
INSERT INTO Genre (name) VALUES ("Australian Country");
INSERT INTO Genre (name) VALUES ("Australian Dance");
INSERT INTO Genre (name) VALUES ("Australian Hip Hop");
INSERT INTO Genre (name) VALUES ("Australian Indie");
INSERT INTO Genre (name) VALUES ("Australian Pop");
INSERT INTO Genre (name) VALUES ("Austrian Hip Hop");
INSERT INTO Genre (name) VALUES ("Austropop");
INSERT INTO Genre (name) VALUES ("Avant-garde");
INSERT INTO Genre (name) VALUES ("Avant-garde Jazz");
INSERT INTO Genre (name) VALUES ("Avantgarde Metal");
INSERT INTO Genre (name) VALUES ("Axe");
INSERT INTO Genre (name) VALUES ("Azonto");
INSERT INTO Genre (name) VALUES ("Bachata");
INSERT INTO Genre (name) VALUES ("Baile Funk");
INSERT INTO Genre (name) VALUES ("Balearic");
INSERT INTO Genre (name) VALUES ("Balkan Beats");
INSERT INTO Genre (name) VALUES ("Balkan Brass");
INSERT INTO Genre (name) VALUES ("Banda");
INSERT INTO Genre (name) VALUES ("Bangla");
INSERT INTO Genre (name) VALUES ("Barbershop");
INSERT INTO Genre (name) VALUES ("Barnemusikk");
INSERT INTO Genre (name) VALUES ("Barnmusik");
INSERT INTO Genre (name) VALUES ("Baroque");
INSERT INTO Genre (name) VALUES ("Baroque Ensemble");
INSERT INTO Genre (name) VALUES ("Basque Rock");
INSERT INTO Genre (name) VALUES ("Bass Music");
INSERT INTO Genre (name) VALUES ("Bass Trip");
INSERT INTO Genre (name) VALUES ("Bassline");
INSERT INTO Genre (name) VALUES ("Bay Area Hip Hop");
INSERT INTO Genre (name) VALUES ("Beach Music");
INSERT INTO Genre (name) VALUES ("Beatdown");
INSERT INTO Genre (name) VALUES ("Beats & Rhymes");
INSERT INTO Genre (name) VALUES ("Bebop");
INSERT INTO Genre (name) VALUES ("Belgian Indie");
INSERT INTO Genre (name) VALUES ("Belgian Rock");
INSERT INTO Genre (name) VALUES ("Belly Dance");
INSERT INTO Genre (name) VALUES ("Belorush");
INSERT INTO Genre (name) VALUES ("Bemani");
INSERT INTO Genre (name) VALUES ("Benga");
INSERT INTO Genre (name) VALUES ("Bhangra");
INSERT INTO Genre (name) VALUES ("Big Band");
INSERT INTO Genre (name) VALUES ("Big Beat");
INSERT INTO Genre (name) VALUES ("Big Room");
INSERT INTO Genre (name) VALUES ("Black Death");
INSERT INTO Genre (name) VALUES ("Black Metal");
INSERT INTO Genre (name) VALUES ("Black Sludge");
INSERT INTO Genre (name) VALUES ("Black Thrash");
INSERT INTO Genre (name) VALUES ("Blackgaze");
INSERT INTO Genre (name) VALUES ("Blaskapelle");
INSERT INTO Genre (name) VALUES ("Bluegrass");
INSERT INTO Genre (name) VALUES ("Blues");
INSERT INTO Genre (name) VALUES ("Blues-rock");
INSERT INTO Genre (name) VALUES ("Blues-rock Guitar");
INSERT INTO Genre (name) VALUES ("Bmore");
INSERT INTO Genre (name) VALUES ("Bolero");
INSERT INTO Genre (name) VALUES ("Boogaloo");
INSERT INTO Genre (name) VALUES ("Boogie-woogie");
INSERT INTO Genre (name) VALUES ("Bossa Nova");
INSERT INTO Genre (name) VALUES ("Bossa Nova Jazz");
INSERT INTO Genre (name) VALUES ("Boston Rock");
INSERT INTO Genre (name) VALUES ("Bounce");
INSERT INTO Genre (name) VALUES ("Bouncy House");
INSERT INTO Genre (name) VALUES ("Bow Pop");
INSERT INTO Genre (name) VALUES ("Boy Band");
INSERT INTO Genre (name) VALUES ("Brass Band");
INSERT INTO Genre (name) VALUES ("Brass Ensemble");
INSERT INTO Genre (name) VALUES ("Brazilian Composition");
INSERT INTO Genre (name) VALUES ("Brazilian Gospel");
INSERT INTO Genre (name) VALUES ("Brazilian Hip Hop");
INSERT INTO Genre (name) VALUES ("Brazilian Indie");
INSERT INTO Genre (name) VALUES ("Brazilian Pop Music");
INSERT INTO Genre (name) VALUES ("Brazilian Punk");
INSERT INTO Genre (name) VALUES ("Breakbeat");
INSERT INTO Genre (name) VALUES ("Breakcore");
INSERT INTO Genre (name) VALUES ("Breaks");
INSERT INTO Genre (name) VALUES ("Brega");
INSERT INTO Genre (name) VALUES ("Breton Folk");
INSERT INTO Genre (name) VALUES ("Brill Building Pop");
INSERT INTO Genre (name) VALUES ("British Alternative Rock");
INSERT INTO Genre (name) VALUES ("British Blues");
INSERT INTO Genre (name) VALUES ("British Brass Band");
INSERT INTO Genre (name) VALUES ("British Dance Band");
INSERT INTO Genre (name) VALUES ("British Folk");
INSERT INTO Genre (name) VALUES ("British Indie Rock");
INSERT INTO Genre (name) VALUES ("British Invasion");
INSERT INTO Genre (name) VALUES ("Britpop");
INSERT INTO Genre (name) VALUES ("Broadway");
INSERT INTO Genre (name) VALUES ("Broken Beat");
INSERT INTO Genre (name) VALUES ("Brooklyn Indie");
INSERT INTO Genre (name) VALUES ("Brostep");
INSERT INTO Genre (name) VALUES ("Brutal Death Metal");
INSERT INTO Genre (name) VALUES ("Brutal Deathcore");
INSERT INTO Genre (name) VALUES ("Bubble Trance");
INSERT INTO Genre (name) VALUES ("Bubblegum Dance");
INSERT INTO Genre (name) VALUES ("Bubblegum Pop");
INSERT INTO Genre (name) VALUES ("Bulgarian Rock");
INSERT INTO Genre (name) VALUES ("Byzantine");
INSERT INTO Genre (name) VALUES ("C-pop");
INSERT INTO Genre (name) VALUES ("C64");
INSERT INTO Genre (name) VALUES ("C86");
INSERT INTO Genre (name) VALUES ("Cabaret");
INSERT INTO Genre (name) VALUES ("Cajun");
INSERT INTO Genre (name) VALUES ("Calypso");
INSERT INTO Genre (name) VALUES ("Canadian Country");
INSERT INTO Genre (name) VALUES ("Canadian Hip Hop");
INSERT INTO Genre (name) VALUES ("Canadian Indie");
INSERT INTO Genre (name) VALUES ("Canadian Metal");
INSERT INTO Genre (name) VALUES ("Canadian Pop");
INSERT INTO Genre (name) VALUES ("Candy Pop");
INSERT INTO Genre (name) VALUES ("Cantautor");
INSERT INTO Genre (name) VALUES ("Cante Flamenco");
INSERT INTO Genre (name) VALUES ("Canterbury Scene");
INSERT INTO Genre (name) VALUES ("Cantopop");
INSERT INTO Genre (name) VALUES ("Canzone Napoletana");
INSERT INTO Genre (name) VALUES ("Capoeira");
INSERT INTO Genre (name) VALUES ("Carnatic");
INSERT INTO Genre (name) VALUES ("Catstep");
INSERT INTO Genre (name) VALUES ("Caucasian Folk");
INSERT INTO Genre (name) VALUES ("Ccm");
INSERT INTO Genre (name) VALUES ("Ceilidh");
INSERT INTO Genre (name) VALUES ("Cello");
INSERT INTO Genre (name) VALUES ("Celtic");
INSERT INTO Genre (name) VALUES ("Celtic Christmas");
INSERT INTO Genre (name) VALUES ("Celtic Punk");
INSERT INTO Genre (name) VALUES ("Celtic Rock");
INSERT INTO Genre (name) VALUES ("Central Asian Folk");
INSERT INTO Genre (name) VALUES ("Chalga");
INSERT INTO Genre (name) VALUES ("Chamber Pop");
INSERT INTO Genre (name) VALUES ("Chanson");
INSERT INTO Genre (name) VALUES ("Chanson Quebecois");
INSERT INTO Genre (name) VALUES ("Chaotic Black Metal");
INSERT INTO Genre (name) VALUES ("Chaotic Hardcore");
INSERT INTO Genre (name) VALUES ("Charred Death");
INSERT INTO Genre (name) VALUES ("Chicago Blues");
INSERT INTO Genre (name) VALUES ("Chicago House");
INSERT INTO Genre (name) VALUES ("Chicago Indie");
INSERT INTO Genre (name) VALUES ("Chicago Soul");
INSERT INTO Genre (name) VALUES ("Chicano Rap");
INSERT INTO Genre (name) VALUES ("Children's Christmas");
INSERT INTO Genre (name) VALUES ("Children's Music");
INSERT INTO Genre (name) VALUES ("Chilean Rock");
INSERT INTO Genre (name) VALUES ("Chill Groove");
INSERT INTO Genre (name) VALUES ("Chill Lounge");
INSERT INTO Genre (name) VALUES ("Chill-out");
INSERT INTO Genre (name) VALUES ("Chill-out Trance");
INSERT INTO Genre (name) VALUES ("Chillstep");
INSERT INTO Genre (name) VALUES ("Chillwave");
INSERT INTO Genre (name) VALUES ("Chinese Indie Rock");
INSERT INTO Genre (name) VALUES ("Chinese Opera");
INSERT INTO Genre (name) VALUES ("Chinese Traditional");
INSERT INTO Genre (name) VALUES ("Chip Hop");
INSERT INTO Genre (name) VALUES ("Chiptune");
INSERT INTO Genre (name) VALUES ("Choral");
INSERT INTO Genre (name) VALUES ("Choro");
INSERT INTO Genre (name) VALUES ("Christian Alternative Rock");
INSERT INTO Genre (name) VALUES ("Christian Christmas");
INSERT INTO Genre (name) VALUES ("Christian Dance");
INSERT INTO Genre (name) VALUES ("Christian Hardcore");
INSERT INTO Genre (name) VALUES ("Christian Hip Hop");
INSERT INTO Genre (name) VALUES ("Christian Metal");
INSERT INTO Genre (name) VALUES ("Christian Music");
INSERT INTO Genre (name) VALUES ("Christian Punk");
INSERT INTO Genre (name) VALUES ("Christian Rock");
INSERT INTO Genre (name) VALUES ("Christmas");
INSERT INTO Genre (name) VALUES ("Christmas Product");
INSERT INTO Genre (name) VALUES ("Cinematic Dubstep");
INSERT INTO Genre (name) VALUES ("Clarinet");
INSERT INTO Genre (name) VALUES ("Classic Afrobeat");
INSERT INTO Genre (name) VALUES ("Classic Belgian Pop");
INSERT INTO Genre (name) VALUES ("Classic Chinese Pop");
INSERT INTO Genre (name) VALUES ("Classic Colombian Pop");
INSERT INTO Genre (name) VALUES ("Classic Czech Pop");
INSERT INTO Genre (name) VALUES ("Classic Danish Pop");
INSERT INTO Genre (name) VALUES ("Classic Dutch Pop");
INSERT INTO Genre (name) VALUES ("Classic Eurovision");
INSERT INTO Genre (name) VALUES ("Classic Finnish Pop");
INSERT INTO Genre (name) VALUES ("Classic Finnish Rock");
INSERT INTO Genre (name) VALUES ("Classic French Pop");
INSERT INTO Genre (name) VALUES ("Classic Funk Rock");
INSERT INTO Genre (name) VALUES ("Classic Garage Rock");
INSERT INTO Genre (name) VALUES ("Classic Italian Pop");
INSERT INTO Genre (name) VALUES ("Classic Norwegian Pop");
INSERT INTO Genre (name) VALUES ("Classic Peruvian Pop");
INSERT INTO Genre (name) VALUES ("Classic Polish Pop");
INSERT INTO Genre (name) VALUES ("Classic Psychedelic Rock");
INSERT INTO Genre (name) VALUES ("Classic Rock");
INSERT INTO Genre (name) VALUES ("Classic Russian Pop");
INSERT INTO Genre (name) VALUES ("Classic Russian Rock");
INSERT INTO Genre (name) VALUES ("Classic Schlager");
INSERT INTO Genre (name) VALUES ("Classic Soundtrack");
INSERT INTO Genre (name) VALUES ("Classic Swedish Pop");
INSERT INTO Genre (name) VALUES ("Classic Turkish Pop");
INSERT INTO Genre (name) VALUES ("Classic Venezuelan Pop");
INSERT INTO Genre (name) VALUES ("Classical");
INSERT INTO Genre (name) VALUES ("Classical Christmas");
INSERT INTO Genre (name) VALUES ("Classical Flute");
INSERT INTO Genre (name) VALUES ("Classical Guitar");
INSERT INTO Genre (name) VALUES ("Classical Organ");
INSERT INTO Genre (name) VALUES ("Classical Performance");
INSERT INTO Genre (name) VALUES ("Classical Period");
INSERT INTO Genre (name) VALUES ("Classical Piano");
INSERT INTO Genre (name) VALUES ("College A Cappella");
INSERT INTO Genre (name) VALUES ("College Marching Band");
INSERT INTO Genre (name) VALUES ("Colombian Rock");
INSERT INTO Genre (name) VALUES ("Columbus Ohio Indie");
INSERT INTO Genre (name) VALUES ("Comedy");
INSERT INTO Genre (name) VALUES ("Comedy Rock");
INSERT INTO Genre (name) VALUES ("Comic");
INSERT INTO Genre (name) VALUES ("Commons");
INSERT INTO Genre (name) VALUES ("Complextro");
INSERT INTO Genre (name) VALUES ("Composition D");
INSERT INTO Genre (name) VALUES ("Concert Piano");
INSERT INTO Genre (name) VALUES ("Consort");
INSERT INTO Genre (name) VALUES ("Contemporary Classical");
INSERT INTO Genre (name) VALUES ("Contemporary Country");
INSERT INTO Genre (name) VALUES ("Contemporary Folk");
INSERT INTO Genre (name) VALUES ("Contemporary Jazz");
INSERT INTO Genre (name) VALUES ("Contemporary Post-bop");
INSERT INTO Genre (name) VALUES ("Cool Jazz");
INSERT INTO Genre (name) VALUES ("Corrosion");
INSERT INTO Genre (name) VALUES ("Corsican Folk");
INSERT INTO Genre (name) VALUES ("Country");
INSERT INTO Genre (name) VALUES ("Country Blues");
INSERT INTO Genre (name) VALUES ("Country Christmas");
INSERT INTO Genre (name) VALUES ("Country Dawn");
INSERT INTO Genre (name) VALUES ("Country Gospel");
INSERT INTO Genre (name) VALUES ("Country Road");
INSERT INTO Genre (name) VALUES ("Country Rock");
INSERT INTO Genre (name) VALUES ("Coupe Decale");
INSERT INTO Genre (name) VALUES ("Coverchill");
INSERT INTO Genre (name) VALUES ("Covertrance");
INSERT INTO Genre (name) VALUES ("Cowboy Western");
INSERT INTO Genre (name) VALUES ("Cowpunk");
INSERT INTO Genre (name) VALUES ("Crack Rock Steady");
INSERT INTO Genre (name) VALUES ("Croatian Pop");
INSERT INTO Genre (name) VALUES ("Crossover Prog");
INSERT INTO Genre (name) VALUES ("Crossover Thrash");
INSERT INTO Genre (name) VALUES ("Crunk");
INSERT INTO Genre (name) VALUES ("Crust Punk");
INSERT INTO Genre (name) VALUES ("Cryptic Black Metal");
INSERT INTO Genre (name) VALUES ("Cuban Rumba");
INSERT INTO Genre (name) VALUES ("Cubaton");
INSERT INTO Genre (name) VALUES ("Cumbia");
INSERT INTO Genre (name) VALUES ("Cumbia Funk");
INSERT INTO Genre (name) VALUES ("Cumbia Sonidera");
INSERT INTO Genre (name) VALUES ("Cumbia Villera");
INSERT INTO Genre (name) VALUES ("Cyber Metal");
INSERT INTO Genre (name) VALUES ("Czech Folk");
INSERT INTO Genre (name) VALUES ("Czech Rock");
INSERT INTO Genre (name) VALUES ("Dallas Indie");
INSERT INTO Genre (name) VALUES ("Dance Pop");
INSERT INTO Genre (name) VALUES ("Dance Rock");
INSERT INTO Genre (name) VALUES ("Dance-punk");
INSERT INTO Genre (name) VALUES ("Dancehall");
INSERT INTO Genre (name) VALUES ("Dangdut");
INSERT INTO Genre (name) VALUES ("Danish Hip Hop");
INSERT INTO Genre (name) VALUES ("Danish Indie");
INSERT INTO Genre (name) VALUES ("Danish Jazz");
INSERT INTO Genre (name) VALUES ("Danish Pop");
INSERT INTO Genre (name) VALUES ("Danish Pop Rock");
INSERT INTO Genre (name) VALUES ("Dansband");
INSERT INTO Genre (name) VALUES ("Danseband");
INSERT INTO Genre (name) VALUES ("Dansktop");
INSERT INTO Genre (name) VALUES ("Dark Ambient");
INSERT INTO Genre (name) VALUES ("Dark Black Metal");
INSERT INTO Genre (name) VALUES ("Dark Cabaret");
INSERT INTO Genre (name) VALUES ("Dark Electro-industrial");
INSERT INTO Genre (name) VALUES ("Dark Hardcore");
INSERT INTO Genre (name) VALUES ("Dark Jazz");
INSERT INTO Genre (name) VALUES ("Dark Minimal Techno");
INSERT INTO Genre (name) VALUES ("Dark Progressive House");
INSERT INTO Genre (name) VALUES ("Dark Psytrance");
INSERT INTO Genre (name) VALUES ("Dark Wave");
INSERT INTO Genre (name) VALUES ("Darkstep");
INSERT INTO Genre (name) VALUES ("Death Core");
INSERT INTO Genre (name) VALUES ("Death Metal");
INSERT INTO Genre (name) VALUES ("Deathgrind");
INSERT INTO Genre (name) VALUES ("Deep Acoustic Pop");
INSERT INTO Genre (name) VALUES ("Deep Adult Standards");
INSERT INTO Genre (name) VALUES ("Deep Alternative R&b");
INSERT INTO Genre (name) VALUES ("Deep Ambient");
INSERT INTO Genre (name) VALUES ("Deep Baroque");
INSERT INTO Genre (name) VALUES ("Deep Brazilian Pop");
INSERT INTO Genre (name) VALUES ("Deep Breakcore");
INSERT INTO Genre (name) VALUES ("Deep Canadian Indie");
INSERT INTO Genre (name) VALUES ("Deep Ccm");
INSERT INTO Genre (name) VALUES ("Deep Cello");
INSERT INTO Genre (name) VALUES ("Deep Chill");
INSERT INTO Genre (name) VALUES ("Deep Chill-out");
INSERT INTO Genre (name) VALUES ("Deep Christian Rock");
INSERT INTO Genre (name) VALUES ("Deep Classic Garage Rock");
INSERT INTO Genre (name) VALUES ("Deep Classical Piano");
INSERT INTO Genre (name) VALUES ("Deep Comedy");
INSERT INTO Genre (name) VALUES ("Deep Contemporary Country");
INSERT INTO Genre (name) VALUES ("Deep Dance Pop");
INSERT INTO Genre (name) VALUES ("Deep Darkpsy");
INSERT INTO Genre (name) VALUES ("Deep Deep House");
INSERT INTO Genre (name) VALUES ("Deep Deep Tech House");
INSERT INTO Genre (name) VALUES ("Deep Delta Blues");
INSERT INTO Genre (name) VALUES ("Deep Disco");
INSERT INTO Genre (name) VALUES ("Deep Disco House");
INSERT INTO Genre (name) VALUES ("Deep Discofox");
INSERT INTO Genre (name) VALUES ("Deep Downtempo Fusion");
INSERT INTO Genre (name) VALUES ("Deep Dub Techno");
INSERT INTO Genre (name) VALUES ("Deep East Coast Hip Hop");
INSERT INTO Genre (name) VALUES ("Deep Euro House");
INSERT INTO Genre (name) VALUES ("Deep Eurodance");
INSERT INTO Genre (name) VALUES ("Deep Filthstep");
INSERT INTO Genre (name) VALUES ("Deep Flow");
INSERT INTO Genre (name) VALUES ("Deep Folk Metal");
INSERT INTO Genre (name) VALUES ("Deep Free Jazz");
INSERT INTO Genre (name) VALUES ("Deep Freestyle");
INSERT INTO Genre (name) VALUES ("Deep Full On");
INSERT INTO Genre (name) VALUES ("Deep Funk");
INSERT INTO Genre (name) VALUES ("Deep Funk House");
INSERT INTO Genre (name) VALUES ("Deep G Funk");
INSERT INTO Genre (name) VALUES ("Deep German Indie");
INSERT INTO Genre (name) VALUES ("Deep German Punk");
INSERT INTO Genre (name) VALUES ("Deep Gothic Post-punk");
INSERT INTO Genre (name) VALUES ("Deep Happy Hardcore");
INSERT INTO Genre (name) VALUES ("Deep Hardcore");
INSERT INTO Genre (name) VALUES ("Deep Hardcore Punk");
INSERT INTO Genre (name) VALUES ("Deep Hardstyle");
INSERT INTO Genre (name) VALUES ("Deep House");
INSERT INTO Genre (name) VALUES ("Deep Indian Pop");
INSERT INTO Genre (name) VALUES ("Deep Indie Pop");
INSERT INTO Genre (name) VALUES ("Deep Indie Rock");
INSERT INTO Genre (name) VALUES ("Deep Indie Singer-songwriter");
INSERT INTO Genre (name) VALUES ("Deep Italo Disco");
INSERT INTO Genre (name) VALUES ("Deep Jazz Fusion");
INSERT INTO Genre (name) VALUES ("Deep Jazz Guitar");
INSERT INTO Genre (name) VALUES ("Deep Jazz Piano");
INSERT INTO Genre (name) VALUES ("Deep Latin Alternative");
INSERT INTO Genre (name) VALUES ("Deep Liquid");
INSERT INTO Genre (name) VALUES ("Deep Liquid Bass");
INSERT INTO Genre (name) VALUES ("Deep Melodic Death Metal");
INSERT INTO Genre (name) VALUES ("Deep Melodic Hard Rock");
INSERT INTO Genre (name) VALUES ("Deep Melodic House");
INSERT INTO Genre (name) VALUES ("Deep Melodic Metalcore");
INSERT INTO Genre (name) VALUES ("Deep Minimal Techno");
INSERT INTO Genre (name) VALUES ("Deep Motown");
INSERT INTO Genre (name) VALUES ("Deep Neo-synthpop");
INSERT INTO Genre (name) VALUES ("Deep Neofolk");
INSERT INTO Genre (name) VALUES ("Deep New Wave");
INSERT INTO Genre (name) VALUES ("Deep Nordic Folk");
INSERT INTO Genre (name) VALUES ("Deep Northern Soul");
INSERT INTO Genre (name) VALUES ("Deep Opera");
INSERT INTO Genre (name) VALUES ("Deep Orchestral");
INSERT INTO Genre (name) VALUES ("Deep Orgcore");
INSERT INTO Genre (name) VALUES ("Deep Pop Emo");
INSERT INTO Genre (name) VALUES ("Deep Pop Punk");
INSERT INTO Genre (name) VALUES ("Deep Power-pop Punk");
INSERT INTO Genre (name) VALUES ("Deep Progressive House");
INSERT INTO Genre (name) VALUES ("Deep Progressive Trance");
INSERT INTO Genre (name) VALUES ("Deep Psychobilly");
INSERT INTO Genre (name) VALUES ("Deep Psytrance");
INSERT INTO Genre (name) VALUES ("Deep Punk Rock");
INSERT INTO Genre (name) VALUES ("Deep Ragga");
INSERT INTO Genre (name) VALUES ("Deep Rai");
INSERT INTO Genre (name) VALUES ("Deep Regional Mexican");
INSERT INTO Genre (name) VALUES ("Deep Smooth Jazz");
INSERT INTO Genre (name) VALUES ("Deep Soft Rock");
INSERT INTO Genre (name) VALUES ("Deep Soul House");
INSERT INTO Genre (name) VALUES ("Deep Soundtrack");
INSERT INTO Genre (name) VALUES ("Deep Southern Soul");
INSERT INTO Genre (name) VALUES ("Deep Space Rock");
INSERT INTO Genre (name) VALUES ("Deep String Quartet");
INSERT INTO Genre (name) VALUES ("Deep Sunset Lounge");
INSERT INTO Genre (name) VALUES ("Deep Surf Music");
INSERT INTO Genre (name) VALUES ("Deep Symphonic Black Metal");
INSERT INTO Genre (name) VALUES ("Deep Talent Show");
INSERT INTO Genre (name) VALUES ("Deep Tech House");
INSERT INTO Genre (name) VALUES ("Deep Thrash Metal");
INSERT INTO Genre (name) VALUES ("Deep Trap");
INSERT INTO Genre (name) VALUES ("Deep Turkish Pop");
INSERT INTO Genre (name) VALUES ("Deep Uplifting Trance");
INSERT INTO Genre (name) VALUES ("Deep Vocal House");
INSERT INTO Genre (name) VALUES ("Deep Vocal Jazz");
INSERT INTO Genre (name) VALUES ("Delta Blues");
INSERT INTO Genre (name) VALUES ("Demoscene");
INSERT INTO Genre (name) VALUES ("Denver Indie");
INSERT INTO Genre (name) VALUES ("Depressive Black Metal");
INSERT INTO Genre (name) VALUES ("Desert Blues");
INSERT INTO Genre (name) VALUES ("Desi");
INSERT INTO Genre (name) VALUES ("Destroy Techno");
INSERT INTO Genre (name) VALUES ("Detroit Hip Hop");
INSERT INTO Genre (name) VALUES ("Detroit Techno");
INSERT INTO Genre (name) VALUES ("Didgeridoo");
INSERT INTO Genre (name) VALUES ("Digital Hardcore");
INSERT INTO Genre (name) VALUES ("Dirty South Rap");
INSERT INTO Genre (name) VALUES ("Dirty Texas Rap");
INSERT INTO Genre (name) VALUES ("Disco");
INSERT INTO Genre (name) VALUES ("Disco House");
INSERT INTO Genre (name) VALUES ("Discofox");
INSERT INTO Genre (name) VALUES ("Dixieland");
INSERT INTO Genre (name) VALUES ("Djent");
INSERT INTO Genre (name) VALUES ("Dominican Pop");
INSERT INTO Genre (name) VALUES ("Doo-wop");
INSERT INTO Genre (name) VALUES ("Doom Metal");
INSERT INTO Genre (name) VALUES ("Doomcore");
INSERT INTO Genre (name) VALUES ("Doujin");
INSERT INTO Genre (name) VALUES ("Downtempo");
INSERT INTO Genre (name) VALUES ("Downtempo Fusion");
INSERT INTO Genre (name) VALUES ("Downtempo Trip Hop");
INSERT INTO Genre (name) VALUES ("Drama");
INSERT INTO Genre (name) VALUES ("Dream Pop");
INSERT INTO Genre (name) VALUES ("Dreamo");
INSERT INTO Genre (name) VALUES ("Drill And Bass");
INSERT INTO Genre (name) VALUES ("Drone");
INSERT INTO Genre (name) VALUES ("Drone Folk");
INSERT INTO Genre (name) VALUES ("Drone Metal");
INSERT INTO Genre (name) VALUES ("Drone Psych");
INSERT INTO Genre (name) VALUES ("Drum And Bass");
INSERT INTO Genre (name) VALUES ("Drumfunk");
INSERT INTO Genre (name) VALUES ("Dub");
INSERT INTO Genre (name) VALUES ("Dub Techno");
INSERT INTO Genre (name) VALUES ("Dubstep");
INSERT INTO Genre (name) VALUES ("Dubstep Product");
INSERT INTO Genre (name) VALUES ("Dubsteppe");
INSERT INTO Genre (name) VALUES ("Duranguense");
INSERT INTO Genre (name) VALUES ("Dutch Hip Hop");
INSERT INTO Genre (name) VALUES ("Dutch House");
INSERT INTO Genre (name) VALUES ("Dutch Pop");
INSERT INTO Genre (name) VALUES ("Dutch Rock");
INSERT INTO Genre (name) VALUES ("E6fi");
INSERT INTO Genre (name) VALUES ("Early Music");
INSERT INTO Genre (name) VALUES ("Early Music Ensemble");
INSERT INTO Genre (name) VALUES ("East Coast Hip Hop");
INSERT INTO Genre (name) VALUES ("East Coast Reggae");
INSERT INTO Genre (name) VALUES ("Easy Listening");
INSERT INTO Genre (name) VALUES ("Ebm");
INSERT INTO Genre (name) VALUES ("Ectofolk");
INSERT INTO Genre (name) VALUES ("Ecuadoria");
INSERT INTO Genre (name) VALUES ("Edm");
INSERT INTO Genre (name) VALUES ("Electric Blues");
INSERT INTO Genre (name) VALUES ("Electro");
INSERT INTO Genre (name) VALUES ("Electro Dub");
INSERT INTO Genre (name) VALUES ("Electro House");
INSERT INTO Genre (name) VALUES ("Electro Jazz");
INSERT INTO Genre (name) VALUES ("Electro Latino");
INSERT INTO Genre (name) VALUES ("Electro Swing");
INSERT INTO Genre (name) VALUES ("Electro Trash");
INSERT INTO Genre (name) VALUES ("Electro-industrial");
INSERT INTO Genre (name) VALUES ("Electroacoustic Improvisation");
INSERT INTO Genre (name) VALUES ("Electroclash");
INSERT INTO Genre (name) VALUES ("Electrofox");
INSERT INTO Genre (name) VALUES ("Electronic");
INSERT INTO Genre (name) VALUES ("Electronica");
INSERT INTO Genre (name) VALUES ("Electronicore");
INSERT INTO Genre (name) VALUES ("Electropowerpop");
INSERT INTO Genre (name) VALUES ("Electropunk");
INSERT INTO Genre (name) VALUES ("Emo");
INSERT INTO Genre (name) VALUES ("Emo Punk");
INSERT INTO Genre (name) VALUES ("Enka");
INSERT INTO Genre (name) VALUES ("Entehno");
INSERT INTO Genre (name) VALUES ("Environmental");
INSERT INTO Genre (name) VALUES ("Epicore");
INSERT INTO Genre (name) VALUES ("Estonian Pop");
INSERT INTO Genre (name) VALUES ("Ethereal Gothic");
INSERT INTO Genre (name) VALUES ("Ethereal Wave");
INSERT INTO Genre (name) VALUES ("Etherpop");
INSERT INTO Genre (name) VALUES ("Ethiopian Pop");
INSERT INTO Genre (name) VALUES ("Eurobeat");
INSERT INTO Genre (name) VALUES ("Eurodance");
INSERT INTO Genre (name) VALUES ("Europop");
INSERT INTO Genre (name) VALUES ("Euroska");
INSERT INTO Genre (name) VALUES ("Eurovision");
INSERT INTO Genre (name) VALUES ("Exotica");
INSERT INTO Genre (name) VALUES ("Experimental");
INSERT INTO Genre (name) VALUES ("Experimental Dubstep");
INSERT INTO Genre (name) VALUES ("Experimental Psych");
INSERT INTO Genre (name) VALUES ("Experimental Rock");
INSERT INTO Genre (name) VALUES ("Fado");
INSERT INTO Genre (name) VALUES ("Fake");
INSERT INTO Genre (name) VALUES ("Fallen Angel");
INSERT INTO Genre (name) VALUES ("Faroese Pop");
INSERT INTO Genre (name) VALUES ("Fast Melodic Punk");
INSERT INTO Genre (name) VALUES ("Fidget House");
INSERT INTO Genre (name) VALUES ("Filmi");
INSERT INTO Genre (name) VALUES ("Filter House");
INSERT INTO Genre (name) VALUES ("Filthstep");
INSERT INTO Genre (name) VALUES ("Fingerstyle");
INSERT INTO Genre (name) VALUES ("Finnish Edm");
INSERT INTO Genre (name) VALUES ("Finnish Hardcore");
INSERT INTO Genre (name) VALUES ("Finnish Hip Hop");
INSERT INTO Genre (name) VALUES ("Finnish Indie");
INSERT INTO Genre (name) VALUES ("Finnish Jazz");
INSERT INTO Genre (name) VALUES ("Finnish Metal");
INSERT INTO Genre (name) VALUES ("Finnish Pop");
INSERT INTO Genre (name) VALUES ("Flamenco");
INSERT INTO Genre (name) VALUES ("Flick Hop");
INSERT INTO Genre (name) VALUES ("Folk");
INSERT INTO Genre (name) VALUES ("Folk Christmas");
INSERT INTO Genre (name) VALUES ("Folk Metal");
INSERT INTO Genre (name) VALUES ("Folk Punk");
INSERT INTO Genre (name) VALUES ("Folk Rock");
INSERT INTO Genre (name) VALUES ("Folk-pop");
INSERT INTO Genre (name) VALUES ("Folk-prog");
INSERT INTO Genre (name) VALUES ("Folklore Argentino");
INSERT INTO Genre (name) VALUES ("Folkmusik");
INSERT INTO Genre (name) VALUES ("Footwork");
INSERT INTO Genre (name) VALUES ("Forro");
INSERT INTO Genre (name) VALUES ("Fourth World");
INSERT INTO Genre (name) VALUES ("Freak Folk");
INSERT INTO Genre (name) VALUES ("Freakbeat");
INSERT INTO Genre (name) VALUES ("Free Improvisation");
INSERT INTO Genre (name) VALUES ("Free Jazz");
INSERT INTO Genre (name) VALUES ("Freestyle");
INSERT INTO Genre (name) VALUES ("French Folk");
INSERT INTO Genre (name) VALUES ("French Folk Pop");
INSERT INTO Genre (name) VALUES ("French Hip Hop");
INSERT INTO Genre (name) VALUES ("French Indie Pop");
INSERT INTO Genre (name) VALUES ("French Movie Tunes");
INSERT INTO Genre (name) VALUES ("French Pop");
INSERT INTO Genre (name) VALUES ("French Punk");
INSERT INTO Genre (name) VALUES ("French Reggae");
INSERT INTO Genre (name) VALUES ("French Rock");
INSERT INTO Genre (name) VALUES ("Full On");
INSERT INTO Genre (name) VALUES ("Funeral Doom");
INSERT INTO Genre (name) VALUES ("Funk");
INSERT INTO Genre (name) VALUES ("Funk Carioca");
INSERT INTO Genre (name) VALUES ("Funk Metal");
INSERT INTO Genre (name) VALUES ("Funk Rock");
INSERT INTO Genre (name) VALUES ("Funky Breaks");
INSERT INTO Genre (name) VALUES ("Future Ambient");
INSERT INTO Genre (name) VALUES ("Future Garage");
INSERT INTO Genre (name) VALUES ("Futurepop");
INSERT INTO Genre (name) VALUES ("G Funk");
INSERT INTO Genre (name) VALUES ("Gabba");
INSERT INTO Genre (name) VALUES ("Galego");
INSERT INTO Genre (name) VALUES ("Gamecore");
INSERT INTO Genre (name) VALUES ("Gamelan");
INSERT INTO Genre (name) VALUES ("Gangster Rap");
INSERT INTO Genre (name) VALUES ("Garage Pop");
INSERT INTO Genre (name) VALUES ("Garage Punk");
INSERT INTO Genre (name) VALUES ("Garage Punk Blues");
INSERT INTO Genre (name) VALUES ("Garage Rock");
INSERT INTO Genre (name) VALUES ("Gauze Pop");
INSERT INTO Genre (name) VALUES ("Gbvfi");
INSERT INTO Genre (name) VALUES ("Geek Folk");
INSERT INTO Genre (name) VALUES ("Geek Rock");
INSERT INTO Genre (name) VALUES ("German Ccm");
INSERT INTO Genre (name) VALUES ("German Hip Hop");
INSERT INTO Genre (name) VALUES ("German Indie");
INSERT INTO Genre (name) VALUES ("German Metal");
INSERT INTO Genre (name) VALUES ("German Oi");
INSERT INTO Genre (name) VALUES ("German Pop");
INSERT INTO Genre (name) VALUES ("German Pop Rock");
INSERT INTO Genre (name) VALUES ("German Punk");
INSERT INTO Genre (name) VALUES ("German Show Tunes");
INSERT INTO Genre (name) VALUES ("German Techno");
INSERT INTO Genre (name) VALUES ("Ghettotech");
INSERT INTO Genre (name) VALUES ("Ghoststep");
INSERT INTO Genre (name) VALUES ("Girl Group");
INSERT INTO Genre (name) VALUES ("Glam Metal");
INSERT INTO Genre (name) VALUES ("Glam Rock");
INSERT INTO Genre (name) VALUES ("Glitch");
INSERT INTO Genre (name) VALUES ("Glitch Beats");
INSERT INTO Genre (name) VALUES ("Glitch Hop");
INSERT INTO Genre (name) VALUES ("Glitter Trance");
INSERT INTO Genre (name) VALUES ("Goa Trance");
INSERT INTO Genre (name) VALUES ("Goregrind");
INSERT INTO Genre (name) VALUES ("Gospel");
INSERT INTO Genre (name) VALUES ("Gospel Blues");
INSERT INTO Genre (name) VALUES ("Gospel Reggae");
INSERT INTO Genre (name) VALUES ("Gothic Alternative");
INSERT INTO Genre (name) VALUES ("Gothic Americana");
INSERT INTO Genre (name) VALUES ("Gothic Doom");
INSERT INTO Genre (name) VALUES ("Gothic Metal");
INSERT INTO Genre (name) VALUES ("Gothic Post-punk");
INSERT INTO Genre (name) VALUES ("Gothic Rock");
INSERT INTO Genre (name) VALUES ("Gothic Symphonic Metal");
INSERT INTO Genre (name) VALUES ("Grave Wave");
INSERT INTO Genre (name) VALUES ("Greek Hip Hop");
INSERT INTO Genre (name) VALUES ("Greek House");
INSERT INTO Genre (name) VALUES ("Greek Indie");
INSERT INTO Genre (name) VALUES ("Grim Death Metal");
INSERT INTO Genre (name) VALUES ("Grime");
INSERT INTO Genre (name) VALUES ("Grindcore");
INSERT INTO Genre (name) VALUES ("Grisly Death Metal");
INSERT INTO Genre (name) VALUES ("Groove Metal");
INSERT INTO Genre (name) VALUES ("Grunge");
INSERT INTO Genre (name) VALUES ("Grunge Pop");
INSERT INTO Genre (name) VALUES ("Grupera");
INSERT INTO Genre (name) VALUES ("Guidance");
INSERT INTO Genre (name) VALUES ("Gypsy Jazz");
INSERT INTO Genre (name) VALUES ("Hands Up");
INSERT INTO Genre (name) VALUES ("Happy Hardcore");
INSERT INTO Genre (name) VALUES ("Hard Alternative");
INSERT INTO Genre (name) VALUES ("Hard Bop");
INSERT INTO Genre (name) VALUES ("Hard Glam");
INSERT INTO Genre (name) VALUES ("Hard House");
INSERT INTO Genre (name) VALUES ("Hard Rock");
INSERT INTO Genre (name) VALUES ("Hard Stoner Rock");
INSERT INTO Genre (name) VALUES ("Hard Trance");
INSERT INTO Genre (name) VALUES ("Hardcore");
INSERT INTO Genre (name) VALUES ("Hardcore Breaks");
INSERT INTO Genre (name) VALUES ("Hardcore Hip Hop");
INSERT INTO Genre (name) VALUES ("Hardcore Punk");
INSERT INTO Genre (name) VALUES ("Hardcore Techno");
INSERT INTO Genre (name) VALUES ("Hardstyle");
INSERT INTO Genre (name) VALUES ("Harmonica Blues");
INSERT INTO Genre (name) VALUES ("Harp");
INSERT INTO Genre (name) VALUES ("Hatecore");
INSERT INTO Genre (name) VALUES ("Hauntology");
INSERT INTO Genre (name) VALUES ("Hawaiian");
INSERT INTO Genre (name) VALUES ("Healing");
INSERT INTO Genre (name) VALUES ("Heavy Alternative");
INSERT INTO Genre (name) VALUES ("Heavy Christmas");
INSERT INTO Genre (name) VALUES ("Heavy Gothic Rock");
INSERT INTO Genre (name) VALUES ("Hi Nrg");
INSERT INTO Genre (name) VALUES ("Highlife");
INSERT INTO Genre (name) VALUES ("Hindustani Classical");
INSERT INTO Genre (name) VALUES ("Hip Hop");
INSERT INTO Genre (name) VALUES ("Hip Hop Quebecois");
INSERT INTO Genre (name) VALUES ("Hip Hop Tuga");
INSERT INTO Genre (name) VALUES ("Hip House");
INSERT INTO Genre (name) VALUES ("Hip Pop");
INSERT INTO Genre (name) VALUES ("Hiplife");
INSERT INTO Genre (name) VALUES ("Hoerspiel");
INSERT INTO Genre (name) VALUES ("Hollywood");
INSERT INTO Genre (name) VALUES ("Honky Tonk");
INSERT INTO Genre (name) VALUES ("Horror Punk");
INSERT INTO Genre (name) VALUES ("Horrorcore");
INSERT INTO Genre (name) VALUES ("House");
INSERT INTO Genre (name) VALUES ("Hungarian Hip Hop");
INSERT INTO Genre (name) VALUES ("Hungarian Pop");
INSERT INTO Genre (name) VALUES ("Hungarian Rock");
INSERT INTO Genre (name) VALUES ("Hurban");
INSERT INTO Genre (name) VALUES ("Hyphy");
INSERT INTO Genre (name) VALUES ("Icelandic Pop");
INSERT INTO Genre (name) VALUES ("Idol");
INSERT INTO Genre (name) VALUES ("Illbient");
INSERT INTO Genre (name) VALUES ("Indian Classical");
INSERT INTO Genre (name) VALUES ("Indian Pop");
INSERT INTO Genre (name) VALUES ("Indian Rock");
INSERT INTO Genre (name) VALUES ("Indie Christmas");
INSERT INTO Genre (name) VALUES ("Indie Dream Pop");
INSERT INTO Genre (name) VALUES ("Indie Emo");
INSERT INTO Genre (name) VALUES ("Indie Emo Rock");
INSERT INTO Genre (name) VALUES ("Indie Folk");
INSERT INTO Genre (name) VALUES ("Indie Fuzzpop");
INSERT INTO Genre (name) VALUES ("Indie Pop");
INSERT INTO Genre (name) VALUES ("Indie Pop Rock");
INSERT INTO Genre (name) VALUES ("Indie Post-punk");
INSERT INTO Genre (name) VALUES ("Indie Psych-pop");
INSERT INTO Genre (name) VALUES ("Indie R&b");
INSERT INTO Genre (name) VALUES ("Indie Rock");
INSERT INTO Genre (name) VALUES ("Indie Shoegaze");
INSERT INTO Genre (name) VALUES ("Indie Singer-songwriter");
INSERT INTO Genre (name) VALUES ("Indietronica");
INSERT INTO Genre (name) VALUES ("Indonesian Indie");
INSERT INTO Genre (name) VALUES ("Indonesian Pop");
INSERT INTO Genre (name) VALUES ("Indorock");
INSERT INTO Genre (name) VALUES ("Industrial");
INSERT INTO Genre (name) VALUES ("Industrial Metal");
INSERT INTO Genre (name) VALUES ("Industrial Rock");
INSERT INTO Genre (name) VALUES ("Instrumental Post Rock");
INSERT INTO Genre (name) VALUES ("Instrumental Rock");
INSERT INTO Genre (name) VALUES ("Intelligent Dance Music");
INSERT INTO Genre (name) VALUES ("Irish Folk");
INSERT INTO Genre (name) VALUES ("Irish Indie");
INSERT INTO Genre (name) VALUES ("Irish Rock");
INSERT INTO Genre (name) VALUES ("Iskelma");
INSERT INTO Genre (name) VALUES ("Islamic Recitation");
INSERT INTO Genre (name) VALUES ("Israeli Rock");
INSERT INTO Genre (name) VALUES ("Italian Disco");
INSERT INTO Genre (name) VALUES ("Italian Folk");
INSERT INTO Genre (name) VALUES ("Italian Hip Hop");
INSERT INTO Genre (name) VALUES ("Italian Indie Pop");
INSERT INTO Genre (name) VALUES ("Italian Jazz");
INSERT INTO Genre (name) VALUES ("Italian Pop");
INSERT INTO Genre (name) VALUES ("Italian Pop Rock");
INSERT INTO Genre (name) VALUES ("Italian Progressive Rock");
INSERT INTO Genre (name) VALUES ("Italian Punk");
INSERT INTO Genre (name) VALUES ("Italo Dance");
INSERT INTO Genre (name) VALUES ("J-alt");
INSERT INTO Genre (name) VALUES ("J-ambient");
INSERT INTO Genre (name) VALUES ("J-core");
INSERT INTO Genre (name) VALUES ("J-dance");
INSERT INTO Genre (name) VALUES ("J-idol");
INSERT INTO Genre (name) VALUES ("J-indie");
INSERT INTO Genre (name) VALUES ("J-metal");
INSERT INTO Genre (name) VALUES ("J-pop");
INSERT INTO Genre (name) VALUES ("J-poppunk");
INSERT INTO Genre (name) VALUES ("J-poprock");
INSERT INTO Genre (name) VALUES ("J-punk");
INSERT INTO Genre (name) VALUES ("J-rap");
INSERT INTO Genre (name) VALUES ("J-rock");
INSERT INTO Genre (name) VALUES ("J-theme");
INSERT INTO Genre (name) VALUES ("Jam Band");
INSERT INTO Genre (name) VALUES ("Jangle Pop");
INSERT INTO Genre (name) VALUES ("Jangle Rock");
INSERT INTO Genre (name) VALUES ("Japanese Jazztronica");
INSERT INTO Genre (name) VALUES ("Japanese Psychedelic");
INSERT INTO Genre (name) VALUES ("Japanese R&b");
INSERT INTO Genre (name) VALUES ("Japanese Standards");
INSERT INTO Genre (name) VALUES ("Japanese Traditional");
INSERT INTO Genre (name) VALUES ("Japanoise");
INSERT INTO Genre (name) VALUES ("Jazz");
INSERT INTO Genre (name) VALUES ("Jazz Bass");
INSERT INTO Genre (name) VALUES ("Jazz Blues");
INSERT INTO Genre (name) VALUES ("Jazz Brass");
INSERT INTO Genre (name) VALUES ("Jazz Christmas");
INSERT INTO Genre (name) VALUES ("Jazz Funk");
INSERT INTO Genre (name) VALUES ("Jazz Fusion");
INSERT INTO Genre (name) VALUES ("Jazz Metal");
INSERT INTO Genre (name) VALUES ("Jazz Orchestra");
INSERT INTO Genre (name) VALUES ("Jazz Rock");
INSERT INTO Genre (name) VALUES ("Jazz Trio");
INSERT INTO Genre (name) VALUES ("Jerk");
INSERT INTO Genre (name) VALUES ("Jig And Reel");
INSERT INTO Genre (name) VALUES ("Judaica");
INSERT INTO Genre (name) VALUES ("Jug Band");
INSERT INTO Genre (name) VALUES ("Juggalo");
INSERT INTO Genre (name) VALUES ("Jump Blues");
INSERT INTO Genre (name) VALUES ("Jump Up");
INSERT INTO Genre (name) VALUES ("Jumpstyle");
INSERT INTO Genre (name) VALUES ("Jungle");
INSERT INTO Genre (name) VALUES ("K-hop");
INSERT INTO Genre (name) VALUES ("K-indie");
INSERT INTO Genre (name) VALUES ("K-pop");
INSERT INTO Genre (name) VALUES ("K-rock");
INSERT INTO Genre (name) VALUES ("Kabarett");
INSERT INTO Genre (name) VALUES ("Karneval");
INSERT INTO Genre (name) VALUES ("Kc Indie");
INSERT INTO Genre (name) VALUES ("Kindermusik");
INSERT INTO Genre (name) VALUES ("Kirtan");
INSERT INTO Genre (name) VALUES ("Kiwi Rock");
INSERT INTO Genre (name) VALUES ("Kizomba");
INSERT INTO Genre (name) VALUES ("Klapa");
INSERT INTO Genre (name) VALUES ("Klezmer");
INSERT INTO Genre (name) VALUES ("Kompa");
INSERT INTO Genre (name) VALUES ("Kraut Rock");
INSERT INTO Genre (name) VALUES ("Kuduro");
INSERT INTO Genre (name) VALUES ("Kurdish Folk");
INSERT INTO Genre (name) VALUES ("Kwaito");
INSERT INTO Genre (name) VALUES ("La Indie");
INSERT INTO Genre (name) VALUES ("Laboratorio");
INSERT INTO Genre (name) VALUES ("Laiko");
INSERT INTO Genre (name) VALUES ("Latin");
INSERT INTO Genre (name) VALUES ("Latin Alternative");
INSERT INTO Genre (name) VALUES ("Latin Christian");
INSERT INTO Genre (name) VALUES ("Latin Christmas");
INSERT INTO Genre (name) VALUES ("Latin Electronica");
INSERT INTO Genre (name) VALUES ("Latin Hip Hop");
INSERT INTO Genre (name) VALUES ("Latin Jazz");
INSERT INTO Genre (name) VALUES ("Latin Metal");
INSERT INTO Genre (name) VALUES ("Latin Pop");
INSERT INTO Genre (name) VALUES ("Latvian Pop");
INSERT INTO Genre (name) VALUES ("Lds");
INSERT INTO Genre (name) VALUES ("Leeds Indie");
INSERT INTO Genre (name) VALUES ("Levenslied");
INSERT INTO Genre (name) VALUES ("Liedermacher");
INSERT INTO Genre (name) VALUES ("Light Music");
INSERT INTO Genre (name) VALUES ("Lilith");
INSERT INTO Genre (name) VALUES ("Liquid Funk");
INSERT INTO Genre (name) VALUES ("Lithumania");
INSERT INTO Genre (name) VALUES ("Liturgical");
INSERT INTO Genre (name) VALUES ("Lo Star");
INSERT INTO Genre (name) VALUES ("Lo-fi");
INSERT INTO Genre (name) VALUES ("Louisiana Blues");
INSERT INTO Genre (name) VALUES ("Louisville Indie");
INSERT INTO Genre (name) VALUES ("Lounge");
INSERT INTO Genre (name) VALUES ("Lounge House");
INSERT INTO Genre (name) VALUES ("Lovers Rock");
INSERT INTO Genre (name) VALUES ("Lowercase");
INSERT INTO Genre (name) VALUES ("Luk Thung");
INSERT INTO Genre (name) VALUES ("Madchester");
INSERT INTO Genre (name) VALUES ("Maghreb");
INSERT INTO Genre (name) VALUES ("Magyar");
INSERT INTO Genre (name) VALUES ("Makossa");
INSERT INTO Genre (name) VALUES ("Malagasy Folk");
INSERT INTO Genre (name) VALUES ("Malaysian Pop");
INSERT INTO Genre (name) VALUES ("Mallet");
INSERT INTO Genre (name) VALUES ("Mambo");
INSERT INTO Genre (name) VALUES ("Mande Pop");
INSERT INTO Genre (name) VALUES ("Mandopop");
INSERT INTO Genre (name) VALUES ("Manele");
INSERT INTO Genre (name) VALUES ("Marching Band");
INSERT INTO Genre (name) VALUES ("Mariachi");
INSERT INTO Genre (name) VALUES ("Martial Industrial");
INSERT INTO Genre (name) VALUES ("Mashup");
INSERT INTO Genre (name) VALUES ("Math Pop");
INSERT INTO Genre (name) VALUES ("Math Rock");
INSERT INTO Genre (name) VALUES ("Mathcore");
INSERT INTO Genre (name) VALUES ("Mbalax");
INSERT INTO Genre (name) VALUES ("Medieval");
INSERT INTO Genre (name) VALUES ("Medieval Rock");
INSERT INTO Genre (name) VALUES ("Meditation");
INSERT INTO Genre (name) VALUES ("Melancholia");
INSERT INTO Genre (name) VALUES ("Melbourne Bounce");
INSERT INTO Genre (name) VALUES ("Mellow Gold");
INSERT INTO Genre (name) VALUES ("Melodic Death Metal");
INSERT INTO Genre (name) VALUES ("Melodic Hard Rock");
INSERT INTO Genre (name) VALUES ("Melodic Hardcore");
INSERT INTO Genre (name) VALUES ("Melodic Metalcore");
INSERT INTO Genre (name) VALUES ("Melodic Power Metal");
INSERT INTO Genre (name) VALUES ("Melodic Progressive Metal");
INSERT INTO Genre (name) VALUES ("Memphis Blues");
INSERT INTO Genre (name) VALUES ("Memphis Hip Hop");
INSERT INTO Genre (name) VALUES ("Memphis Soul");
INSERT INTO Genre (name) VALUES ("Merengue");
INSERT INTO Genre (name) VALUES ("Merengue Urbano");
INSERT INTO Genre (name) VALUES ("Merseybeat");
INSERT INTO Genre (name) VALUES ("Metal");
INSERT INTO Genre (name) VALUES ("Metalcore");
INSERT INTO Genre (name) VALUES ("Metropopolis");
INSERT INTO Genre (name) VALUES ("Mexican Indie");
INSERT INTO Genre (name) VALUES ("Mexican Rock-and-roll");
INSERT INTO Genre (name) VALUES ("Mexican Son");
INSERT INTO Genre (name) VALUES ("Mexican Traditional");
INSERT INTO Genre (name) VALUES ("Miami Bass");
INSERT INTO Genre (name) VALUES ("Michigan Indie");
INSERT INTO Genre (name) VALUES ("Microhouse");
INSERT INTO Genre (name) VALUES ("Military Band");
INSERT INTO Genre (name) VALUES ("Minimal");
INSERT INTO Genre (name) VALUES ("Minimal Dub");
INSERT INTO Genre (name) VALUES ("Minimal Dubstep");
INSERT INTO Genre (name) VALUES ("Minimal Melodic Techno");
INSERT INTO Genre (name) VALUES ("Minimal Tech House");
INSERT INTO Genre (name) VALUES ("Minimal Techno");
INSERT INTO Genre (name) VALUES ("Minimal Wave");
INSERT INTO Genre (name) VALUES ("Mizrahi");
INSERT INTO Genre (name) VALUES ("Mod Revival");
INSERT INTO Genre (name) VALUES ("Modern Blues");
INSERT INTO Genre (name) VALUES ("Modern Classical");
INSERT INTO Genre (name) VALUES ("Modern Country Rock");
INSERT INTO Genre (name) VALUES ("Modern Downshift");
INSERT INTO Genre (name) VALUES ("Modern Free Jazz");
INSERT INTO Genre (name) VALUES ("Modern Performance");
INSERT INTO Genre (name) VALUES ("Modern Southern Rock");
INSERT INTO Genre (name) VALUES ("Modern Uplift");
INSERT INTO Genre (name) VALUES ("Monastic");
INSERT INTO Genre (name) VALUES ("Moombahton");
INSERT INTO Genre (name) VALUES ("Morna");
INSERT INTO Genre (name) VALUES ("Motivation");
INSERT INTO Genre (name) VALUES ("Motown");
INSERT INTO Genre (name) VALUES ("Movie Tunes");
INSERT INTO Genre (name) VALUES ("Mpb");
INSERT INTO Genre (name) VALUES ("Musica Para Ninos");
INSERT INTO Genre (name) VALUES ("Musiikkia Lapsille");
INSERT INTO Genre (name) VALUES ("Musique Concrete");
INSERT INTO Genre (name) VALUES ("Musique Pour Enfants");
INSERT INTO Genre (name) VALUES ("Muziek Voor Kinderen");
INSERT INTO Genre (name) VALUES ("Nasheed");
INSERT INTO Genre (name) VALUES ("Nashville Sound");
INSERT INTO Genre (name) VALUES ("Native American");
INSERT INTO Genre (name) VALUES ("Necrogrind");
INSERT INTO Genre (name) VALUES ("Neo Classical Metal");
INSERT INTO Genre (name) VALUES ("Neo Honky Tonk");
INSERT INTO Genre (name) VALUES ("Neo Mellow");
INSERT INTO Genre (name) VALUES ("Neo Metal");
INSERT INTO Genre (name) VALUES ("Neo Soul");
INSERT INTO Genre (name) VALUES ("Neo Soul-jazz");
INSERT INTO Genre (name) VALUES ("Neo-industrial Rock");
INSERT INTO Genre (name) VALUES ("Neo-pagan");
INSERT INTO Genre (name) VALUES ("Neo-progressive");
INSERT INTO Genre (name) VALUES ("Neo-psychedelic");
INSERT INTO Genre (name) VALUES ("Neo-rockabilly");
INSERT INTO Genre (name) VALUES ("Neo-singer-songwriter");
INSERT INTO Genre (name) VALUES ("Neo-synthpop");
INSERT INTO Genre (name) VALUES ("Neo-trad Metal");
INSERT INTO Genre (name) VALUES ("Neo-traditional Country");
INSERT INTO Genre (name) VALUES ("Neoclassical");
INSERT INTO Genre (name) VALUES ("Neofolk");
INSERT INTO Genre (name) VALUES ("Nepali");
INSERT INTO Genre (name) VALUES ("Nerdcore");
INSERT INTO Genre (name) VALUES ("Neue Deutsche Harte");
INSERT INTO Genre (name) VALUES ("Neue Deutsche Welle");
INSERT INTO Genre (name) VALUES ("Neurofunk");
INSERT INTO Genre (name) VALUES ("Neurostep");
INSERT INTO Genre (name) VALUES ("New Age");
INSERT INTO Genre (name) VALUES ("New Age Piano");
INSERT INTO Genre (name) VALUES ("New Americana");
INSERT INTO Genre (name) VALUES ("New Beat");
INSERT INTO Genre (name) VALUES ("New Jack Smooth");
INSERT INTO Genre (name) VALUES ("New Jack Swing");
INSERT INTO Genre (name) VALUES ("New Orleans Blues");
INSERT INTO Genre (name) VALUES ("New Orleans Jazz");
INSERT INTO Genre (name) VALUES ("New Rave");
INSERT INTO Genre (name) VALUES ("New Romantic");
INSERT INTO Genre (name) VALUES ("New Tribe");
INSERT INTO Genre (name) VALUES ("New Wave");
INSERT INTO Genre (name) VALUES ("New Wave Pop");
INSERT INTO Genre (name) VALUES ("New Weird America");
INSERT INTO Genre (name) VALUES ("Ninja");
INSERT INTO Genre (name) VALUES ("Nintendocore");
INSERT INTO Genre (name) VALUES ("Nl Folk");
INSERT INTO Genre (name) VALUES ("No Wave");
INSERT INTO Genre (name) VALUES ("Noise");
INSERT INTO Genre (name) VALUES ("Noise Pop");
INSERT INTO Genre (name) VALUES ("Noise Punk");
INSERT INTO Genre (name) VALUES ("Noise Rock");
INSERT INTO Genre (name) VALUES ("Nordic Folk");
INSERT INTO Genre (name) VALUES ("Nordic House");
INSERT INTO Genre (name) VALUES ("Norteno");
INSERT INTO Genre (name) VALUES ("Northern Irish Indie");
INSERT INTO Genre (name) VALUES ("Northern Soul");
INSERT INTO Genre (name) VALUES ("Norwegian Gospel");
INSERT INTO Genre (name) VALUES ("Norwegian Hip Hop");
INSERT INTO Genre (name) VALUES ("Norwegian Jazz");
INSERT INTO Genre (name) VALUES ("Norwegian Metal");
INSERT INTO Genre (name) VALUES ("Norwegian Pop");
INSERT INTO Genre (name) VALUES ("Norwegian Punk");
INSERT INTO Genre (name) VALUES ("Norwegian Rock");
INSERT INTO Genre (name) VALUES ("Nu Age");
INSERT INTO Genre (name) VALUES ("Nu Disco");
INSERT INTO Genre (name) VALUES ("Nu Electro");
INSERT INTO Genre (name) VALUES ("Nu Gaze");
INSERT INTO Genre (name) VALUES ("Nu Jazz");
INSERT INTO Genre (name) VALUES ("Nu Metal");
INSERT INTO Genre (name) VALUES ("Nu Skool Breaks");
INSERT INTO Genre (name) VALUES ("Nu-cumbia");
INSERT INTO Genre (name) VALUES ("Nueva Cancion");
INSERT INTO Genre (name) VALUES ("Nursery");
INSERT INTO Genre (name) VALUES ("Nwobhm");
INSERT INTO Genre (name) VALUES ("Nwothm");
INSERT INTO Genre (name) VALUES ("Nz Indie");
INSERT INTO Genre (name) VALUES ("Oi");
INSERT INTO Genre (name) VALUES ("Old School Hip Hop");
INSERT INTO Genre (name) VALUES ("Old-time");
INSERT INTO Genre (name) VALUES ("Opera");
INSERT INTO Genre (name) VALUES ("Operatic Pop");
INSERT INTO Genre (name) VALUES ("Opm");
INSERT INTO Genre (name) VALUES ("Oratory");
INSERT INTO Genre (name) VALUES ("Orchestral");
INSERT INTO Genre (name) VALUES ("Organic Ambient");
INSERT INTO Genre (name) VALUES ("Orgcore");
INSERT INTO Genre (name) VALUES ("Orquesta Tipica");
INSERT INTO Genre (name) VALUES ("Orquesta Tropical");
INSERT INTO Genre (name) VALUES ("Oshare Kei");
INSERT INTO Genre (name) VALUES ("Ostrock");
INSERT INTO Genre (name) VALUES ("Outer Hip Hop");
INSERT INTO Genre (name) VALUES ("Outlaw Country");
INSERT INTO Genre (name) VALUES ("Outsider");
INSERT INTO Genre (name) VALUES ("Outsider House");
INSERT INTO Genre (name) VALUES ("P Funk");
INSERT INTO Genre (name) VALUES ("Pagan Black Metal");
INSERT INTO Genre (name) VALUES ("Pagode");
INSERT INTO Genre (name) VALUES ("Pakistani Pop");
INSERT INTO Genre (name) VALUES ("Permanent Wave");
INSERT INTO Genre (name) VALUES ("Persian Pop");
INSERT INTO Genre (name) VALUES ("Persian Traditional");
INSERT INTO Genre (name) VALUES ("Perth Indie");
INSERT INTO Genre (name) VALUES ("Peruvian Rock");
INSERT INTO Genre (name) VALUES ("Piano Blues");
INSERT INTO Genre (name) VALUES ("Piano Rock");
INSERT INTO Genre (name) VALUES ("Piedmont Blues");
INSERT INTO Genre (name) VALUES ("Pipe Band");
INSERT INTO Genre (name) VALUES ("Poetry");
INSERT INTO Genre (name) VALUES ("Polish Hip Hop");
INSERT INTO Genre (name) VALUES ("Polish Indie");
INSERT INTO Genre (name) VALUES ("Polish Jazz");
INSERT INTO Genre (name) VALUES ("Polish Pop");
INSERT INTO Genre (name) VALUES ("Polish Punk");
INSERT INTO Genre (name) VALUES ("Polish Reggae");
INSERT INTO Genre (name) VALUES ("Polka");
INSERT INTO Genre (name) VALUES ("Polynesian Pop");
INSERT INTO Genre (name) VALUES ("Polyphony");
INSERT INTO Genre (name) VALUES ("Pop");
INSERT INTO Genre (name) VALUES ("Pop Christmas");
INSERT INTO Genre (name) VALUES ("Pop Emo");
INSERT INTO Genre (name) VALUES ("Pop House");
INSERT INTO Genre (name) VALUES ("Pop Punk");
INSERT INTO Genre (name) VALUES ("Pop Rap");
INSERT INTO Genre (name) VALUES ("Pop Rock");
INSERT INTO Genre (name) VALUES ("Popgaze");
INSERT INTO Genre (name) VALUES ("Porro");
INSERT INTO Genre (name) VALUES ("Portland Indie");
INSERT INTO Genre (name) VALUES ("Portuguese Pop");
INSERT INTO Genre (name) VALUES ("Portuguese Rock");
INSERT INTO Genre (name) VALUES ("Post Rock");
INSERT INTO Genre (name) VALUES ("Post-disco");
INSERT INTO Genre (name) VALUES ("Post-disco Soul");
INSERT INTO Genre (name) VALUES ("Post-grunge");
INSERT INTO Genre (name) VALUES ("Post-hardcore");
INSERT INTO Genre (name) VALUES ("Post-metal");
INSERT INTO Genre (name) VALUES ("Post-post-hardcore");
INSERT INTO Genre (name) VALUES ("Post-punk");
INSERT INTO Genre (name) VALUES ("Power Blues-rock");
INSERT INTO Genre (name) VALUES ("Power Electronics");
INSERT INTO Genre (name) VALUES ("Power Metal");
INSERT INTO Genre (name) VALUES ("Power Noise");
INSERT INTO Genre (name) VALUES ("Power Pop");
INSERT INTO Genre (name) VALUES ("Power Violence");
INSERT INTO Genre (name) VALUES ("Power-pop Punk");
INSERT INTO Genre (name) VALUES ("Praise");
INSERT INTO Genre (name) VALUES ("Progressive Alternative");
INSERT INTO Genre (name) VALUES ("Progressive Bluegrass");
INSERT INTO Genre (name) VALUES ("Progressive Electro House");
INSERT INTO Genre (name) VALUES ("Progressive House");
INSERT INTO Genre (name) VALUES ("Progressive Metal");
INSERT INTO Genre (name) VALUES ("Progressive Psytrance");
INSERT INTO Genre (name) VALUES ("Progressive Rock");
INSERT INTO Genre (name) VALUES ("Progressive Trance");
INSERT INTO Genre (name) VALUES ("Progressive Trance House");
INSERT INTO Genre (name) VALUES ("Progressive Uplifting Trance");
INSERT INTO Genre (name) VALUES ("Protopunk");
INSERT INTO Genre (name) VALUES ("Psych Gaze");
INSERT INTO Genre (name) VALUES ("Psychedelic Blues-rock");
INSERT INTO Genre (name) VALUES ("Psychedelic Rock");
INSERT INTO Genre (name) VALUES ("Psychedelic Trance");
INSERT INTO Genre (name) VALUES ("Psychill");
INSERT INTO Genre (name) VALUES ("Psychobilly");
INSERT INTO Genre (name) VALUES ("Pub Rock");
INSERT INTO Genre (name) VALUES ("Puerto Rican Rock");
INSERT INTO Genre (name) VALUES ("Punjabi");
INSERT INTO Genre (name) VALUES ("Punk");
INSERT INTO Genre (name) VALUES ("Punk Blues");
INSERT INTO Genre (name) VALUES ("Punk Christmas");
INSERT INTO Genre (name) VALUES ("Punk Ska");
INSERT INTO Genre (name) VALUES ("Qawwali");
INSERT INTO Genre (name) VALUES ("Quebecois");
INSERT INTO Genre (name) VALUES ("Quiet Storm");
INSERT INTO Genre (name) VALUES ("R&b");
INSERT INTO Genre (name) VALUES ("Ragga Jungle");
INSERT INTO Genre (name) VALUES ("Ragtime");
INSERT INTO Genre (name) VALUES ("Rai");
INSERT INTO Genre (name) VALUES ("Ranchera");
INSERT INTO Genre (name) VALUES ("Rap");
INSERT INTO Genre (name) VALUES ("Rap Metal");
INSERT INTO Genre (name) VALUES ("Rap Metalcore");
INSERT INTO Genre (name) VALUES ("Rap Rock");
INSERT INTO Genre (name) VALUES ("Raw Black Metal");
INSERT INTO Genre (name) VALUES ("Re:techno");
INSERT INTO Genre (name) VALUES ("Reading");
INSERT INTO Genre (name) VALUES ("Rebetiko");
INSERT INTO Genre (name) VALUES ("Reggae");
INSERT INTO Genre (name) VALUES ("Reggae Fusion");
INSERT INTO Genre (name) VALUES ("Reggae Rock");
INSERT INTO Genre (name) VALUES ("Reggaeton");
INSERT INTO Genre (name) VALUES ("Regional Mexican");
INSERT INTO Genre (name) VALUES ("Relaxative");
INSERT INTO Genre (name) VALUES ("Remix");
INSERT INTO Genre (name) VALUES ("Renaissance");
INSERT INTO Genre (name) VALUES ("Retro Electro");
INSERT INTO Genre (name) VALUES ("Retro Metal");
INSERT INTO Genre (name) VALUES ("Rhythm And Boogie");
INSERT INTO Genre (name) VALUES ("Riddim");
INSERT INTO Genre (name) VALUES ("Rio De La Plata");
INSERT INTO Genre (name) VALUES ("Riot Grrrl");
INSERT INTO Genre (name) VALUES ("Rock");
INSERT INTO Genre (name) VALUES ("Rock Catala");
INSERT INTO Genre (name) VALUES ("Rock En Espanol");
INSERT INTO Genre (name) VALUES ("Rock Gaucho");
INSERT INTO Genre (name) VALUES ("Rock Noise");
INSERT INTO Genre (name) VALUES ("Rock Steady");
INSERT INTO Genre (name) VALUES ("Rock-and-roll");
INSERT INTO Genre (name) VALUES ("Rockabilly");
INSERT INTO Genre (name) VALUES ("Romanian Pop");
INSERT INTO Genre (name) VALUES ("Romanian Rock");
INSERT INTO Genre (name) VALUES ("Romantic");
INSERT INTO Genre (name) VALUES ("Roots Reggae");
INSERT INTO Genre (name) VALUES ("Roots Rock");
INSERT INTO Genre (name) VALUES ("Rumba");
INSERT INTO Genre (name) VALUES ("Russian Alternative");
INSERT INTO Genre (name) VALUES ("Russian Hip Hop");
INSERT INTO Genre (name) VALUES ("Russian Pop");
INSERT INTO Genre (name) VALUES ("Russian Punk");
INSERT INTO Genre (name) VALUES ("Russian Rock");
INSERT INTO Genre (name) VALUES ("Rva Indie");
INSERT INTO Genre (name) VALUES ("Salsa");
INSERT INTO Genre (name) VALUES ("Salsa International");
INSERT INTO Genre (name) VALUES ("Samba");
INSERT INTO Genre (name) VALUES ("Saxophone");
INSERT INTO Genre (name) VALUES ("Schlager");
INSERT INTO Genre (name) VALUES ("Schranz");
INSERT INTO Genre (name) VALUES ("Scorecore");
INSERT INTO Genre (name) VALUES ("Scottish Rock");
INSERT INTO Genre (name) VALUES ("Scratch");
INSERT INTO Genre (name) VALUES ("Screamo");
INSERT INTO Genre (name) VALUES ("Screamo Punk");
INSERT INTO Genre (name) VALUES ("Screamocore");
INSERT INTO Genre (name) VALUES ("Seattle Indie");
INSERT INTO Genre (name) VALUES ("Sega");
INSERT INTO Genre (name) VALUES ("Serialism");
INSERT INTO Genre (name) VALUES ("Sertanejo");
INSERT INTO Genre (name) VALUES ("Sertanejo Tradicional");
INSERT INTO Genre (name) VALUES ("Sertanejo Universitario");
INSERT INTO Genre (name) VALUES ("Sevdah");
INSERT INTO Genre (name) VALUES ("Shanty");
INSERT INTO Genre (name) VALUES ("Sheffield Indie");
INSERT INTO Genre (name) VALUES ("Shibuya-kei");
INSERT INTO Genre (name) VALUES ("Shimmer Pop");
INSERT INTO Genre (name) VALUES ("Shimmer Psych");
INSERT INTO Genre (name) VALUES ("Shiver Pop");
INSERT INTO Genre (name) VALUES ("Shoegaze");
INSERT INTO Genre (name) VALUES ("Show Tunes");
INSERT INTO Genre (name) VALUES ("Singaporean Pop");
INSERT INTO Genre (name) VALUES ("Singer-songwriter");
INSERT INTO Genre (name) VALUES ("Sinhala");
INSERT INTO Genre (name) VALUES ("Ska");
INSERT INTO Genre (name) VALUES ("Ska Punk");
INSERT INTO Genre (name) VALUES ("Ska Revival");
INSERT INTO Genre (name) VALUES ("Skate Punk");
INSERT INTO Genre (name) VALUES ("Skiffle");
INSERT INTO Genre (name) VALUES ("Skinhead Oi");
INSERT INTO Genre (name) VALUES ("Skinhead Reggae");
INSERT INTO Genre (name) VALUES ("Skweee");
INSERT INTO Genre (name) VALUES ("Slam Death Metal");
INSERT INTO Genre (name) VALUES ("Slash Punk");
INSERT INTO Genre (name) VALUES ("Slc Indie");
INSERT INTO Genre (name) VALUES ("Sleaze Rock");
INSERT INTO Genre (name) VALUES ("Sleep");
INSERT INTO Genre (name) VALUES ("Slovak Hip Hop");
INSERT INTO Genre (name) VALUES ("Slovak Pop");
INSERT INTO Genre (name) VALUES ("Slovenian Rock");
INSERT INTO Genre (name) VALUES ("Slow Core");
INSERT INTO Genre (name) VALUES ("Sludge Metal");
INSERT INTO Genre (name) VALUES ("Smooth Jazz");
INSERT INTO Genre (name) VALUES ("Smooth Urban R&b");
INSERT INTO Genre (name) VALUES ("Soca");
INSERT INTO Genre (name) VALUES ("Soda Pop");
INSERT INTO Genre (name) VALUES ("Soft Rock");
INSERT INTO Genre (name) VALUES ("Solipsynthm");
INSERT INTO Genre (name) VALUES ("Soukous");
INSERT INTO Genre (name) VALUES ("Soul");
INSERT INTO Genre (name) VALUES ("Soul Blues");
INSERT INTO Genre (name) VALUES ("Soul Christmas");
INSERT INTO Genre (name) VALUES ("Soul Flow");
INSERT INTO Genre (name) VALUES ("Soul Jazz");
INSERT INTO Genre (name) VALUES ("Soundtrack");
INSERT INTO Genre (name) VALUES ("South African Jazz");
INSERT INTO Genre (name) VALUES ("South Asian Metal");
INSERT INTO Genre (name) VALUES ("Southern Gospel");
INSERT INTO Genre (name) VALUES ("Southern Hip Hop");
INSERT INTO Genre (name) VALUES ("Southern Rock");
INSERT INTO Genre (name) VALUES ("Southern Soul");
INSERT INTO Genre (name) VALUES ("Southern Soul Blues");
INSERT INTO Genre (name) VALUES ("Space Rock");
INSERT INTO Genre (name) VALUES ("Spanish Classical");
INSERT INTO Genre (name) VALUES ("Spanish Folk");
INSERT INTO Genre (name) VALUES ("Spanish Hip Hop");
INSERT INTO Genre (name) VALUES ("Spanish Indie Pop");
INSERT INTO Genre (name) VALUES ("Spanish Indie Rock");
INSERT INTO Genre (name) VALUES ("Spanish Invasion");
INSERT INTO Genre (name) VALUES ("Spanish New Wave");
INSERT INTO Genre (name) VALUES ("Spanish Pop");
INSERT INTO Genre (name) VALUES ("Spanish Pop Rock");
INSERT INTO Genre (name) VALUES ("Spanish Punk");
INSERT INTO Genre (name) VALUES ("Spanish Reggae");
INSERT INTO Genre (name) VALUES ("Speed Garage");
INSERT INTO Genre (name) VALUES ("Speed Metal");
INSERT INTO Genre (name) VALUES ("Speedcore");
INSERT INTO Genre (name) VALUES ("Speed Up Brasileiro");
INSERT INTO Genre (name) VALUES ("Spoken Word");
INSERT INTO Genre (name) VALUES ("Spytrack");
INSERT INTO Genre (name) VALUES ("Steampunk");
INSERT INTO Genre (name) VALUES ("Steelpan");
INSERT INTO Genre (name) VALUES ("Stl Indie");
INSERT INTO Genre (name) VALUES ("Stomp And Flutter");
INSERT INTO Genre (name) VALUES ("Stomp And Holler");
INSERT INTO Genre (name) VALUES ("Stomp And Whittle");
INSERT INTO Genre (name) VALUES ("Stomp Pop");
INSERT INTO Genre (name) VALUES ("Stoner Metal");
INSERT INTO Genre (name) VALUES ("Stoner Rock");
INSERT INTO Genre (name) VALUES ("Straight Edge");
INSERT INTO Genre (name) VALUES ("Street Punk");
INSERT INTO Genre (name) VALUES ("Stride");
INSERT INTO Genre (name) VALUES ("String Band");
INSERT INTO Genre (name) VALUES ("String Folk");
INSERT INTO Genre (name) VALUES ("String Quartet");
INSERT INTO Genre (name) VALUES ("Substep");
INSERT INTO Genre (name) VALUES ("Sunset Lounge");
INSERT INTO Genre (name) VALUES ("Suomi Rock");
INSERT INTO Genre (name) VALUES ("Surf Music");
INSERT INTO Genre (name) VALUES ("Swamp Blues");
INSERT INTO Genre (name) VALUES ("Swamp Pop");
INSERT INTO Genre (name) VALUES ("Swedish Alternative Rock");
INSERT INTO Genre (name) VALUES ("Swedish Hard Rock");
INSERT INTO Genre (name) VALUES ("Swedish Hip Hop");
INSERT INTO Genre (name) VALUES ("Swedish Indie Pop");
INSERT INTO Genre (name) VALUES ("Swedish Indie Rock");
INSERT INTO Genre (name) VALUES ("Swedish Jazz");
INSERT INTO Genre (name) VALUES ("Swedish Metal");
INSERT INTO Genre (name) VALUES ("Swedish Pop");
INSERT INTO Genre (name) VALUES ("Swedish Pop Punk");
INSERT INTO Genre (name) VALUES ("Swedish Prog");
INSERT INTO Genre (name) VALUES ("Swedish Punk");
INSERT INTO Genre (name) VALUES ("Swedish Reggae");
INSERT INTO Genre (name) VALUES ("Swedish Soft Pop");
INSERT INTO Genre (name) VALUES ("Swedish Synthpop");
INSERT INTO Genre (name) VALUES ("Swing");
INSERT INTO Genre (name) VALUES ("Swirl Psych");
INSERT INTO Genre (name) VALUES ("Swiss Folk");
INSERT INTO Genre (name) VALUES ("Swiss Hip Hop");
INSERT INTO Genre (name) VALUES ("Swiss Rock");
INSERT INTO Genre (name) VALUES ("Symphonic Black Metal");
INSERT INTO Genre (name) VALUES ("Symphonic Metal");
INSERT INTO Genre (name) VALUES ("Symphonic Rock");
INSERT INTO Genre (name) VALUES ("Synthpop");
INSERT INTO Genre (name) VALUES ("Taiwanese Pop");
INSERT INTO Genre (name) VALUES ("Talent Show");
INSERT INTO Genre (name) VALUES ("Tango");
INSERT INTO Genre (name) VALUES ("Tech House");
INSERT INTO Genre (name) VALUES ("Technical Brutal Death Metal");
INSERT INTO Genre (name) VALUES ("Technical Death Metal");
INSERT INTO Genre (name) VALUES ("Techno");
INSERT INTO Genre (name) VALUES ("Teen Pop");
INSERT INTO Genre (name) VALUES ("Tejano");
INSERT INTO Genre (name) VALUES ("Tekno");
INSERT INTO Genre (name) VALUES ("Terrorcore");
INSERT INTO Genre (name) VALUES ("Texas Blues");
INSERT INTO Genre (name) VALUES ("Texas Country");
INSERT INTO Genre (name) VALUES ("Thai Indie");
INSERT INTO Genre (name) VALUES ("Thai Pop");
INSERT INTO Genre (name) VALUES ("Thrash Core");
INSERT INTO Genre (name) VALUES ("Thrash Metal");
INSERT INTO Genre (name) VALUES ("Thrash-groove Metal");
INSERT INTO Genre (name) VALUES ("Throat Singing");
INSERT INTO Genre (name) VALUES ("Tibetan");
INSERT INTO Genre (name) VALUES ("Tico");
INSERT INTO Genre (name) VALUES ("Timba");
INSERT INTO Genre (name) VALUES ("Tin Pan Alley");
INSERT INTO Genre (name) VALUES ("Traditional Blues");
INSERT INTO Genre (name) VALUES ("Traditional British Folk");
INSERT INTO Genre (name) VALUES ("Traditional Country");
INSERT INTO Genre (name) VALUES ("Traditional Folk");
INSERT INTO Genre (name) VALUES ("Traditional Funk");
INSERT INTO Genre (name) VALUES ("Traditional Irish Folk");
INSERT INTO Genre (name) VALUES ("Traditional Reggae");
INSERT INTO Genre (name) VALUES ("Traditional Rock 'N Roll");
INSERT INTO Genre (name) VALUES ("Traditional Rockabilly");
INSERT INTO Genre (name) VALUES ("Traditional Scottish Folk");
INSERT INTO Genre (name) VALUES ("Traditional Ska");
INSERT INTO Genre (name) VALUES ("Traditional Soul");
INSERT INTO Genre (name) VALUES ("Traditional Swing");
INSERT INTO Genre (name) VALUES ("Trance");
INSERT INTO Genre (name) VALUES ("Trance Hop");
INSERT INTO Genre (name) VALUES ("Trap Music");
INSERT INTO Genre (name) VALUES ("Trapstep");
INSERT INTO Genre (name) VALUES ("Trash Rock");
INSERT INTO Genre (name) VALUES ("Triangle Indie");
INSERT INTO Genre (name) VALUES ("Tribal House");
INSERT INTO Genre (name) VALUES ("Tribute");
INSERT INTO Genre (name) VALUES ("Trip Hop");
INSERT INTO Genre (name) VALUES ("Tropical");
INSERT INTO Genre (name) VALUES ("Trova");
INSERT INTO Genre (name) VALUES ("Turbo Folk");
INSERT INTO Genre (name) VALUES ("Turkish Alternative");
INSERT INTO Genre (name) VALUES ("Turkish Classical");
INSERT INTO Genre (name) VALUES ("Turkish Folk");
INSERT INTO Genre (name) VALUES ("Turkish Hip Hop");
INSERT INTO Genre (name) VALUES ("Turkish Jazz");
INSERT INTO Genre (name) VALUES ("Turkish Pop");
INSERT INTO Genre (name) VALUES ("Turkish Rock");
INSERT INTO Genre (name) VALUES ("Turntablism");
INSERT INTO Genre (name) VALUES ("Twee Indie Pop");
INSERT INTO Genre (name) VALUES ("Twee Pop");
INSERT INTO Genre (name) VALUES ("Twin Cities Indie");
INSERT INTO Genre (name) VALUES ("Tzadik");
INSERT INTO Genre (name) VALUES ("Uk Dub");
INSERT INTO Genre (name) VALUES ("Uk Garage");
INSERT INTO Genre (name) VALUES ("Uk Hip Hop");
INSERT INTO Genre (name) VALUES ("Uk Post-punk");
INSERT INTO Genre (name) VALUES ("Ukrainian Rock");
INSERT INTO Genre (name) VALUES ("Ukulele");
INSERT INTO Genre (name) VALUES ("Unblack Metal");
INSERT INTO Genre (name) VALUES ("Underground Hip Hop");
INSERT INTO Genre (name) VALUES ("Underground Latin Hip Hop");
INSERT INTO Genre (name) VALUES ("Underground Pop Rap");
INSERT INTO Genre (name) VALUES ("Underground Power Pop");
INSERT INTO Genre (name) VALUES ("Underground Rap");
INSERT INTO Genre (name) VALUES ("Uplifting Trance");
INSERT INTO Genre (name) VALUES ("Urban Contemporary");
INSERT INTO Genre (name) VALUES ("Vallenato");
INSERT INTO Genre (name) VALUES ("Vancouver Indie");
INSERT INTO Genre (name) VALUES ("Vapor House");
INSERT INTO Genre (name) VALUES ("Vaporwave");
INSERT INTO Genre (name) VALUES ("Vegan Straight Edge");
INSERT INTO Genre (name) VALUES ("Vegas Indie");
INSERT INTO Genre (name) VALUES ("Velha Guarda");
INSERT INTO Genre (name) VALUES ("Venezuelan Rock");
INSERT INTO Genre (name) VALUES ("Video Game Music");
INSERT INTO Genre (name) VALUES ("Vienna Indie");
INSERT INTO Genre (name) VALUES ("Vietnamese Pop");
INSERT INTO Genre (name) VALUES ("Viking Metal");
INSERT INTO Genre (name) VALUES ("Vintage Chanson");
INSERT INTO Genre (name) VALUES ("Vintage Country Folk");
INSERT INTO Genre (name) VALUES ("Vintage Gospel");
INSERT INTO Genre (name) VALUES ("Vintage Jazz");
INSERT INTO Genre (name) VALUES ("Vintage Reggae");
INSERT INTO Genre (name) VALUES ("Vintage Rockabilly");
INSERT INTO Genre (name) VALUES ("Vintage Schlager");
INSERT INTO Genre (name) VALUES ("Vintage Swedish Pop");
INSERT INTO Genre (name) VALUES ("Vintage Swing");
INSERT INTO Genre (name) VALUES ("Vintage Swoon");
INSERT INTO Genre (name) VALUES ("Vintage Tango");
INSERT INTO Genre (name) VALUES ("Vintage Western");
INSERT INTO Genre (name) VALUES ("Violin");
INSERT INTO Genre (name) VALUES ("Viral Pop");
INSERT INTO Genre (name) VALUES ("Visual Kei");
INSERT INTO Genre (name) VALUES ("Vocal House");
INSERT INTO Genre (name) VALUES ("Vocal Jazz");
INSERT INTO Genre (name) VALUES ("Vocaloid");
INSERT INTO Genre (name) VALUES ("Volksmusik");
INSERT INTO Genre (name) VALUES ("Warm Drone");
INSERT INTO Genre (name) VALUES ("Welsh Rock");
INSERT INTO Genre (name) VALUES ("West African Jazz");
INSERT INTO Genre (name) VALUES ("West Coast Rap");
INSERT INTO Genre (name) VALUES ("Western Swing");
INSERT INTO Genre (name) VALUES ("Wind Ensemble");
INSERT INTO Genre (name) VALUES ("Witch House");
INSERT INTO Genre (name) VALUES ("Wonky");
INSERT INTO Genre (name) VALUES ("Workout");
INSERT INTO Genre (name) VALUES ("World");
INSERT INTO Genre (name) VALUES ("World Chill");
INSERT INTO Genre (name) VALUES ("World Christmas");
INSERT INTO Genre (name) VALUES ("World Fusion");
INSERT INTO Genre (name) VALUES ("Worship");
INSERT INTO Genre (name) VALUES ("Wrestling");
INSERT INTO Genre (name) VALUES ("Wrock");
INSERT INTO Genre (name) VALUES ("Ye Ye");
INSERT INTO Genre (name) VALUES ("Yoik");
INSERT INTO Genre (name) VALUES ("Yugoslav Rock");
INSERT INTO Genre (name) VALUES ("Zeuhl");
INSERT INTO Genre (name) VALUES ("Zillertal");
INSERT INTO Genre (name) VALUES ("Zim");
INSERT INTO Genre (name) VALUES ("Zolo");
INSERT INTO Genre (name) VALUES ("Zouglou");
INSERT INTO Genre (name) VALUES ("Zouk");
INSERT INTO Genre (name) VALUES ("Zydeco");
