CREATE TABLE Genre (
  id AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL UNIQUE,
  listened_time SMALLINT DEFAULT 0
);

-- Thanks to https://gist.github.com/andytlr/4104c667a62d8145aa3a for the list
INSERT INTO Genre (id, name) VALUES (1, "A Cappella");
INSERT INTO Genre (id, name) VALUES (2, "Abstract");
INSERT INTO Genre (id, name) VALUES (3, "Abstract Beats");
INSERT INTO Genre (id, name) VALUES (4, "Abstract Hip Hop");
INSERT INTO Genre (id, name) VALUES (5, "Abstract Idm");
INSERT INTO Genre (id, name) VALUES (6, "Abstractro");
INSERT INTO Genre (id, name) VALUES (7, "Accordion");
INSERT INTO Genre (id, name) VALUES (8, "Acid House");
INSERT INTO Genre (id, name) VALUES (9, "Acid Jazz");
INSERT INTO Genre (id, name) VALUES (10, "Acid Techno");
INSERT INTO Genre (id, name) VALUES (11, "Acousmatic");
INSERT INTO Genre (id, name) VALUES (12, "Acoustic Blues");
INSERT INTO Genre (id, name) VALUES (13, "Acoustic Pop");
INSERT INTO Genre (id, name) VALUES (14, "Adult Standards");
INSERT INTO Genre (id, name) VALUES (15, "African Percussion");
INSERT INTO Genre (id, name) VALUES (16, "African Rock");
INSERT INTO Genre (id, name) VALUES (17, "Afrikaans");
INSERT INTO Genre (id, name) VALUES (18, "Afrobeat");
INSERT INTO Genre (id, name) VALUES (19, "Afrobeats");
INSERT INTO Genre (id, name) VALUES (20, "Aggrotech");
INSERT INTO Genre (id, name) VALUES (21, "Albanian Pop");
INSERT INTO Genre (id, name) VALUES (22, "Album Rock");
INSERT INTO Genre (id, name) VALUES (23, "Albuquerque Indie");
INSERT INTO Genre (id, name) VALUES (24, "Alternative Americana");
INSERT INTO Genre (id, name) VALUES (25, "Alternative Country");
INSERT INTO Genre (id, name) VALUES (26, "Alternative Dance");
INSERT INTO Genre (id, name) VALUES (27, "Alternative Emo");
INSERT INTO Genre (id, name) VALUES (28, "Alternative Hardcore");
INSERT INTO Genre (id, name) VALUES (29, "Alternative Hip Hop");
INSERT INTO Genre (id, name) VALUES (30, "Alternative Metal");
INSERT INTO Genre (id, name) VALUES (31, "Alternative Metalcore");
INSERT INTO Genre (id, name) VALUES (32, "Alternative New Age");
INSERT INTO Genre (id, name) VALUES (33, "Alternative Pop");
INSERT INTO Genre (id, name) VALUES (34, "Alternative Pop Rock");
INSERT INTO Genre (id, name) VALUES (35, "Alternative R&b");
INSERT INTO Genre (id, name) VALUES (36, "Alternative Rock");
INSERT INTO Genre (id, name) VALUES (37, "Alternative Roots Rock");
INSERT INTO Genre (id, name) VALUES (38, "Ambeat");
INSERT INTO Genre (id, name) VALUES (39, "Ambient");
INSERT INTO Genre (id, name) VALUES (40, "Ambient Dub Techno");
INSERT INTO Genre (id, name) VALUES (41, "Ambient Fusion");
INSERT INTO Genre (id, name) VALUES (42, "Ambient Idm");
INSERT INTO Genre (id, name) VALUES (43, "Ambient Psychill");
INSERT INTO Genre (id, name) VALUES (44, "Ambient Trance");
INSERT INTO Genre (id, name) VALUES (45, "Anarcho-punk");
INSERT INTO Genre (id, name) VALUES (46, "Andean");
INSERT INTO Genre (id, name) VALUES (47, "Anime");
INSERT INTO Genre (id, name) VALUES (48, "Anime Score");
INSERT INTO Genre (id, name) VALUES (49, "Anti-folk");
INSERT INTO Genre (id, name) VALUES (50, "Antiviral Pop");
INSERT INTO Genre (id, name) VALUES (51, "Appalachian Folk");
INSERT INTO Genre (id, name) VALUES (52, "Arab Folk");
INSERT INTO Genre (id, name) VALUES (53, "Arab Pop");
INSERT INTO Genre (id, name) VALUES (54, "Arabesk");
INSERT INTO Genre (id, name) VALUES (55, "Argentine Indie");
INSERT INTO Genre (id, name) VALUES (56, "Argentine Reggae");
INSERT INTO Genre (id, name) VALUES (57, "Argentine Rock");
INSERT INTO Genre (id, name) VALUES (58, "Armenian Folk");
INSERT INTO Genre (id, name) VALUES (59, "Art Rock");
INSERT INTO Genre (id, name) VALUES (60, "Athens Indie");
INSERT INTO Genre (id, name) VALUES (61, "Atmospheric Black Metal");
INSERT INTO Genre (id, name) VALUES (62, "Atmospheric Post Rock");
INSERT INTO Genre (id, name) VALUES (63, "Atmospheric Post-metal");
INSERT INTO Genre (id, name) VALUES (64, "Aussietronica");
INSERT INTO Genre (id, name) VALUES (65, "Austindie");
INSERT INTO Genre (id, name) VALUES (66, "Australian Alternative Rock");
INSERT INTO Genre (id, name) VALUES (67, "Australian Country");
INSERT INTO Genre (id, name) VALUES (68, "Australian Dance");
INSERT INTO Genre (id, name) VALUES (69, "Australian Hip Hop");
INSERT INTO Genre (id, name) VALUES (70, "Australian Indie");
INSERT INTO Genre (id, name) VALUES (71, "Australian Pop");
INSERT INTO Genre (id, name) VALUES (72, "Austrian Hip Hop");
INSERT INTO Genre (id, name) VALUES (73, "Austropop");
INSERT INTO Genre (id, name) VALUES (74, "Avant-garde");
INSERT INTO Genre (id, name) VALUES (75, "Avant-garde Jazz");
INSERT INTO Genre (id, name) VALUES (76, "Avantgarde Metal");
INSERT INTO Genre (id, name) VALUES (77, "Axe");
INSERT INTO Genre (id, name) VALUES (78, "Azonto");
INSERT INTO Genre (id, name) VALUES (79, "Bachata");
INSERT INTO Genre (id, name) VALUES (80, "Baile Funk");
INSERT INTO Genre (id, name) VALUES (81, "Balearic");
INSERT INTO Genre (id, name) VALUES (82, "Balkan Brass");
INSERT INTO Genre (id, name) VALUES (83, "Banda");
INSERT INTO Genre (id, name) VALUES (84, "Bangla");
INSERT INTO Genre (id, name) VALUES (85, "Barbershop");
INSERT INTO Genre (id, name) VALUES (86, "Barnemusikk");
INSERT INTO Genre (id, name) VALUES (87, "Barnmusik");
INSERT INTO Genre (id, name) VALUES (88, "Baroque");
INSERT INTO Genre (id, name) VALUES (89, "Baroque Ensemble");
INSERT INTO Genre (id, name) VALUES (90, "Basque Rock");
INSERT INTO Genre (id, name) VALUES (91, "Bass Music");
INSERT INTO Genre (id, name) VALUES (92, "Bass Trip");
INSERT INTO Genre (id, name) VALUES (93, "Bassline");
INSERT INTO Genre (id, name) VALUES (94, "Bay Area Hip Hop");
INSERT INTO Genre (id, name) VALUES (95, "Beach Music");
INSERT INTO Genre (id, name) VALUES (96, "Beatdown");
INSERT INTO Genre (id, name) VALUES (97, "Beats & Rhymes");
INSERT INTO Genre (id, name) VALUES (98, "Bebop");
INSERT INTO Genre (id, name) VALUES (99, "Belgian Indie");
INSERT INTO Genre (id, name) VALUES (100, "Belgian Rock");
INSERT INTO Genre (id, name) VALUES (101, "Belly Dance");
INSERT INTO Genre (id, name) VALUES (102, "Belorush");
INSERT INTO Genre (id, name) VALUES (103, "Bemani");
INSERT INTO Genre (id, name) VALUES (104, "Benga");
INSERT INTO Genre (id, name) VALUES (105, "Bhangra");
INSERT INTO Genre (id, name) VALUES (106, "Big Band");
INSERT INTO Genre (id, name) VALUES (107, "Big Beat");
INSERT INTO Genre (id, name) VALUES (108, "Big Room");
INSERT INTO Genre (id, name) VALUES (109, "Black Death");
INSERT INTO Genre (id, name) VALUES (110, "Black Metal");
INSERT INTO Genre (id, name) VALUES (111, "Black Sludge");
INSERT INTO Genre (id, name) VALUES (112, "Black Thrash");
INSERT INTO Genre (id, name) VALUES (113, "Blackgaze");
INSERT INTO Genre (id, name) VALUES (114, "Blaskapelle");
INSERT INTO Genre (id, name) VALUES (115, "Bluegrass");
INSERT INTO Genre (id, name) VALUES (116, "Blues");
INSERT INTO Genre (id, name) VALUES (117, "Blues-rock");
INSERT INTO Genre (id, name) VALUES (118, "Blues-rock Guitar");
INSERT INTO Genre (id, name) VALUES (119, "Bmore");
INSERT INTO Genre (id, name) VALUES (120, "Bolero");
INSERT INTO Genre (id, name) VALUES (121, "Boogaloo");
INSERT INTO Genre (id, name) VALUES (122, "Boogie-woogie");
INSERT INTO Genre (id, name) VALUES (123, "Bossa Nova");
INSERT INTO Genre (id, name) VALUES (124, "Bossa Nova Jazz");
INSERT INTO Genre (id, name) VALUES (125, "Boston Rock");
INSERT INTO Genre (id, name) VALUES (126, "Bounce");
INSERT INTO Genre (id, name) VALUES (127, "Bouncy House");
INSERT INTO Genre (id, name) VALUES (128, "Bow Pop");
INSERT INTO Genre (id, name) VALUES (129, "Boy Band");
INSERT INTO Genre (id, name) VALUES (130, "Brass Band");
INSERT INTO Genre (id, name) VALUES (131, "Brass Ensemble");
INSERT INTO Genre (id, name) VALUES (132, "Brazilian Composition");
INSERT INTO Genre (id, name) VALUES (133, "Brazilian Gospel");
INSERT INTO Genre (id, name) VALUES (134, "Brazilian Hip Hop");
INSERT INTO Genre (id, name) VALUES (135, "Brazilian Indie");
INSERT INTO Genre (id, name) VALUES (136, "Brazilian Pop Music");
INSERT INTO Genre (id, name) VALUES (137, "Brazilian Punk");
INSERT INTO Genre (id, name) VALUES (138, "Breakbeat");
INSERT INTO Genre (id, name) VALUES (139, "Breakcore");
INSERT INTO Genre (id, name) VALUES (140, "Breaks");
INSERT INTO Genre (id, name) VALUES (141, "Brega");
INSERT INTO Genre (id, name) VALUES (142, "Breton Folk");
INSERT INTO Genre (id, name) VALUES (143, "Brill Building Pop");
INSERT INTO Genre (id, name) VALUES (144, "British Alternative Rock");
INSERT INTO Genre (id, name) VALUES (145, "British Blues");
INSERT INTO Genre (id, name) VALUES (146, "British Brass Band");
INSERT INTO Genre (id, name) VALUES (147, "British Dance Band");
INSERT INTO Genre (id, name) VALUES (148, "British Folk");
INSERT INTO Genre (id, name) VALUES (149, "British Indie Rock");
INSERT INTO Genre (id, name) VALUES (150, "British Invasion");
INSERT INTO Genre (id, name) VALUES (151, "Britpop");
INSERT INTO Genre (id, name) VALUES (152, "Broadway");
INSERT INTO Genre (id, name) VALUES (153, "Broken Beat");
INSERT INTO Genre (id, name) VALUES (154, "Brooklyn Indie");
INSERT INTO Genre (id, name) VALUES (155, "Brostep");
INSERT INTO Genre (id, name) VALUES (156, "Brutal Death Metal");
INSERT INTO Genre (id, name) VALUES (157, "Brutal Deathcore");
INSERT INTO Genre (id, name) VALUES (158, "Bubble Trance");
INSERT INTO Genre (id, name) VALUES (159, "Bubblegum Dance");
INSERT INTO Genre (id, name) VALUES (160, "Bubblegum Pop");
INSERT INTO Genre (id, name) VALUES (161, "Bulgarian Rock");
INSERT INTO Genre (id, name) VALUES (162, "Byzantine");
INSERT INTO Genre (id, name) VALUES (163, "C-pop");
INSERT INTO Genre (id, name) VALUES (164, "C64");
INSERT INTO Genre (id, name) VALUES (165, "C86");
INSERT INTO Genre (id, name) VALUES (166, "Cabaret");
INSERT INTO Genre (id, name) VALUES (167, "Cajun");
INSERT INTO Genre (id, name) VALUES (168, "Calypso");
INSERT INTO Genre (id, name) VALUES (169, "Canadian Country");
INSERT INTO Genre (id, name) VALUES (170, "Canadian Hip Hop");
INSERT INTO Genre (id, name) VALUES (171, "Canadian Indie");
INSERT INTO Genre (id, name) VALUES (172, "Canadian Metal");
INSERT INTO Genre (id, name) VALUES (173, "Canadian Pop");
INSERT INTO Genre (id, name) VALUES (174, "Candy Pop");
INSERT INTO Genre (id, name) VALUES (175, "Cantautor");
INSERT INTO Genre (id, name) VALUES (176, "Cante Flamenco");
INSERT INTO Genre (id, name) VALUES (177, "Canterbury Scene");
INSERT INTO Genre (id, name) VALUES (178, "Cantopop");
INSERT INTO Genre (id, name) VALUES (179, "Canzone Napoletana");
INSERT INTO Genre (id, name) VALUES (180, "Capoeira");
INSERT INTO Genre (id, name) VALUES (181, "Carnatic");
INSERT INTO Genre (id, name) VALUES (182, "Catstep");
INSERT INTO Genre (id, name) VALUES (183, "Caucasian Folk");
INSERT INTO Genre (id, name) VALUES (184, "Ccm");
INSERT INTO Genre (id, name) VALUES (185, "Ceilidh");
INSERT INTO Genre (id, name) VALUES (186, "Cello");
INSERT INTO Genre (id, name) VALUES (187, "Celtic");
INSERT INTO Genre (id, name) VALUES (188, "Celtic Christmas");
INSERT INTO Genre (id, name) VALUES (189, "Celtic Punk");
INSERT INTO Genre (id, name) VALUES (190, "Celtic Rock");
INSERT INTO Genre (id, name) VALUES (191, "Central Asian Folk");
INSERT INTO Genre (id, name) VALUES (192, "Chalga");
INSERT INTO Genre (id, name) VALUES (193, "Chamber Pop");
INSERT INTO Genre (id, name) VALUES (194, "Chanson");
INSERT INTO Genre (id, name) VALUES (195, "Chanson Quebecois");
INSERT INTO Genre (id, name) VALUES (196, "Chaotic Black Metal");
INSERT INTO Genre (id, name) VALUES (197, "Chaotic Hardcore");
INSERT INTO Genre (id, name) VALUES (198, "Charred Death");
INSERT INTO Genre (id, name) VALUES (199, "Chicago Blues");
INSERT INTO Genre (id, name) VALUES (200, "Chicago House");
INSERT INTO Genre (id, name) VALUES (201, "Chicago Indie");
INSERT INTO Genre (id, name) VALUES (202, "Chicago Soul");
INSERT INTO Genre (id, name) VALUES (203, "Chicano Rap");
INSERT INTO Genre (id, name) VALUES (204, "Children's Christmas");
INSERT INTO Genre (id, name) VALUES (205, "Children's Music");
INSERT INTO Genre (id, name) VALUES (206, "Chilean Rock");
INSERT INTO Genre (id, name) VALUES (207, "Chill Groove");
INSERT INTO Genre (id, name) VALUES (208, "Chill Lounge");
INSERT INTO Genre (id, name) VALUES (209, "Chill-out");
INSERT INTO Genre (id, name) VALUES (210, "Chill-out Trance");
INSERT INTO Genre (id, name) VALUES (211, "Chillstep");
INSERT INTO Genre (id, name) VALUES (212, "Chillwave");
INSERT INTO Genre (id, name) VALUES (213, "Chinese Indie Rock");
INSERT INTO Genre (id, name) VALUES (214, "Chinese Opera");
INSERT INTO Genre (id, name) VALUES (215, "Chinese Traditional");
INSERT INTO Genre (id, name) VALUES (216, "Chip Hop");
INSERT INTO Genre (id, name) VALUES (217, "Chiptune");
INSERT INTO Genre (id, name) VALUES (218, "Choral");
INSERT INTO Genre (id, name) VALUES (219, "Choro");
INSERT INTO Genre (id, name) VALUES (220, "Christian Alternative Rock");
INSERT INTO Genre (id, name) VALUES (221, "Christian Christmas");
INSERT INTO Genre (id, name) VALUES (222, "Christian Dance");
INSERT INTO Genre (id, name) VALUES (223, "Christian Hardcore");
INSERT INTO Genre (id, name) VALUES (224, "Christian Hip Hop");
INSERT INTO Genre (id, name) VALUES (225, "Christian Metal");
INSERT INTO Genre (id, name) VALUES (226, "Christian Music");
INSERT INTO Genre (id, name) VALUES (227, "Christian Punk");
INSERT INTO Genre (id, name) VALUES (228, "Christian Rock");
INSERT INTO Genre (id, name) VALUES (229, "Christmas");
INSERT INTO Genre (id, name) VALUES (230, "Christmas Product");
INSERT INTO Genre (id, name) VALUES (231, "Cinematic Dubstep");
INSERT INTO Genre (id, name) VALUES (232, "Clarinet");
INSERT INTO Genre (id, name) VALUES (233, "Classic Afrobeat");
INSERT INTO Genre (id, name) VALUES (234, "Classic Belgian Pop");
INSERT INTO Genre (id, name) VALUES (235, "Classic Chinese Pop");
INSERT INTO Genre (id, name) VALUES (236, "Classic Colombian Pop");
INSERT INTO Genre (id, name) VALUES (237, "Classic Czech Pop");
INSERT INTO Genre (id, name) VALUES (238, "Classic Danish Pop");
INSERT INTO Genre (id, name) VALUES (239, "Classic Dutch Pop");
INSERT INTO Genre (id, name) VALUES (240, "Classic Eurovision");
INSERT INTO Genre (id, name) VALUES (241, "Classic Finnish Pop");
INSERT INTO Genre (id, name) VALUES (242, "Classic Finnish Rock");
INSERT INTO Genre (id, name) VALUES (243, "Classic French Pop");
INSERT INTO Genre (id, name) VALUES (244, "Classic Funk Rock");
INSERT INTO Genre (id, name) VALUES (245, "Classic Garage Rock");
INSERT INTO Genre (id, name) VALUES (246, "Classic Italian Pop");
INSERT INTO Genre (id, name) VALUES (247, "Classic Norwegian Pop");
INSERT INTO Genre (id, name) VALUES (248, "Classic Peruvian Pop");
INSERT INTO Genre (id, name) VALUES (249, "Classic Polish Pop");
INSERT INTO Genre (id, name) VALUES (250, "Classic Psychedelic Rock");
INSERT INTO Genre (id, name) VALUES (251, "Classic Rock");
INSERT INTO Genre (id, name) VALUES (252, "Classic Russian Pop");
INSERT INTO Genre (id, name) VALUES (253, "Classic Russian Rock");
INSERT INTO Genre (id, name) VALUES (254, "Classic Schlager");
INSERT INTO Genre (id, name) VALUES (255, "Classic Soundtrack");
INSERT INTO Genre (id, name) VALUES (256, "Classic Swedish Pop");
INSERT INTO Genre (id, name) VALUES (257, "Classic Turkish Pop");
INSERT INTO Genre (id, name) VALUES (258, "Classic Venezuelan Pop");
INSERT INTO Genre (id, name) VALUES (259, "Classical");
INSERT INTO Genre (id, name) VALUES (260, "Classical Christmas");
INSERT INTO Genre (id, name) VALUES (261, "Classical Flute");
INSERT INTO Genre (id, name) VALUES (262, "Classical Guitar");
INSERT INTO Genre (id, name) VALUES (263, "Classical Organ");
INSERT INTO Genre (id, name) VALUES (264, "Classical Performance");
INSERT INTO Genre (id, name) VALUES (265, "Classical Period");
INSERT INTO Genre (id, name) VALUES (266, "Classical Piano");
INSERT INTO Genre (id, name) VALUES (267, "College A Cappella");
INSERT INTO Genre (id, name) VALUES (268, "College Marching Band");
INSERT INTO Genre (id, name) VALUES (269, "Colombian Rock");
INSERT INTO Genre (id, name) VALUES (270, "Columbus Ohio Indie");
INSERT INTO Genre (id, name) VALUES (271, "Comedy");
INSERT INTO Genre (id, name) VALUES (272, "Comedy Rock");
INSERT INTO Genre (id, name) VALUES (273, "Comic");
INSERT INTO Genre (id, name) VALUES (274, "Commons");
INSERT INTO Genre (id, name) VALUES (275, "Complextro");
INSERT INTO Genre (id, name) VALUES (276, "Composition D");
INSERT INTO Genre (id, name) VALUES (277, "Concert Piano");
INSERT INTO Genre (id, name) VALUES (278, "Consort");
INSERT INTO Genre (id, name) VALUES (279, "Contemporary Classical");
INSERT INTO Genre (id, name) VALUES (280, "Contemporary Country");
INSERT INTO Genre (id, name) VALUES (281, "Contemporary Folk");
INSERT INTO Genre (id, name) VALUES (282, "Contemporary Jazz");
INSERT INTO Genre (id, name) VALUES (283, "Contemporary Post-bop");
INSERT INTO Genre (id, name) VALUES (284, "Cool Jazz");
INSERT INTO Genre (id, name) VALUES (285, "Corrosion");
INSERT INTO Genre (id, name) VALUES (286, "Corsican Folk");
INSERT INTO Genre (id, name) VALUES (287, "Country");
INSERT INTO Genre (id, name) VALUES (288, "Country Blues");
INSERT INTO Genre (id, name) VALUES (289, "Country Christmas");
INSERT INTO Genre (id, name) VALUES (290, "Country Dawn");
INSERT INTO Genre (id, name) VALUES (291, "Country Gospel");
INSERT INTO Genre (id, name) VALUES (292, "Country Road");
INSERT INTO Genre (id, name) VALUES (293, "Country Rock");
INSERT INTO Genre (id, name) VALUES (294, "Coupe Decale");
INSERT INTO Genre (id, name) VALUES (295, "Coverchill");
INSERT INTO Genre (id, name) VALUES (296, "Covertrance");
INSERT INTO Genre (id, name) VALUES (297, "Cowboy Western");
INSERT INTO Genre (id, name) VALUES (298, "Cowpunk");
INSERT INTO Genre (id, name) VALUES (299, "Crack Rock Steady");
INSERT INTO Genre (id, name) VALUES (300, "Croatian Pop");
INSERT INTO Genre (id, name) VALUES (301, "Crossover Prog");
INSERT INTO Genre (id, name) VALUES (302, "Crossover Thrash");
INSERT INTO Genre (id, name) VALUES (303, "Crunk");
INSERT INTO Genre (id, name) VALUES (304, "Crust Punk");
INSERT INTO Genre (id, name) VALUES (305, "Cryptic Black Metal");
INSERT INTO Genre (id, name) VALUES (306, "Cuban Rumba");
INSERT INTO Genre (id, name) VALUES (307, "Cubaton");
INSERT INTO Genre (id, name) VALUES (308, "Cumbia");
INSERT INTO Genre (id, name) VALUES (309, "Cumbia Funk");
INSERT INTO Genre (id, name) VALUES (310, "Cumbia Sonidera");
INSERT INTO Genre (id, name) VALUES (311, "Cumbia Villera");
INSERT INTO Genre (id, name) VALUES (312, "Cyber Metal");
INSERT INTO Genre (id, name) VALUES (313, "Czech Folk");
INSERT INTO Genre (id, name) VALUES (314, "Czech Rock");
INSERT INTO Genre (id, name) VALUES (315, "Dallas Indie");
INSERT INTO Genre (id, name) VALUES (316, "Dance Pop");
INSERT INTO Genre (id, name) VALUES (317, "Dance Rock");
INSERT INTO Genre (id, name) VALUES (318, "Dance-punk");
INSERT INTO Genre (id, name) VALUES (319, "Dancehall");
INSERT INTO Genre (id, name) VALUES (320, "Dangdut");
INSERT INTO Genre (id, name) VALUES (321, "Danish Hip Hop");
INSERT INTO Genre (id, name) VALUES (322, "Danish Indie");
INSERT INTO Genre (id, name) VALUES (323, "Danish Jazz");
INSERT INTO Genre (id, name) VALUES (324, "Danish Pop");
INSERT INTO Genre (id, name) VALUES (325, "Danish Pop Rock");
INSERT INTO Genre (id, name) VALUES (326, "Dansband");
INSERT INTO Genre (id, name) VALUES (327, "Danseband");
INSERT INTO Genre (id, name) VALUES (328, "Dansktop");
INSERT INTO Genre (id, name) VALUES (329, "Dark Ambient");
INSERT INTO Genre (id, name) VALUES (330, "Dark Black Metal");
INSERT INTO Genre (id, name) VALUES (331, "Dark Cabaret");
INSERT INTO Genre (id, name) VALUES (332, "Dark Electro-industrial");
INSERT INTO Genre (id, name) VALUES (333, "Dark Hardcore");
INSERT INTO Genre (id, name) VALUES (334, "Dark Jazz");
INSERT INTO Genre (id, name) VALUES (335, "Dark Minimal Techno");
INSERT INTO Genre (id, name) VALUES (336, "Dark Progressive House");
INSERT INTO Genre (id, name) VALUES (337, "Dark Psytrance");
INSERT INTO Genre (id, name) VALUES (338, "Dark Wave");
INSERT INTO Genre (id, name) VALUES (339, "Darkstep");
INSERT INTO Genre (id, name) VALUES (340, "Death Core");
INSERT INTO Genre (id, name) VALUES (341, "Death Metal");
INSERT INTO Genre (id, name) VALUES (342, "Deathgrind");
INSERT INTO Genre (id, name) VALUES (343, "Deep Acoustic Pop");
INSERT INTO Genre (id, name) VALUES (344, "Deep Adult Standards");
INSERT INTO Genre (id, name) VALUES (345, "Deep Alternative R&b");
INSERT INTO Genre (id, name) VALUES (346, "Deep Ambient");
INSERT INTO Genre (id, name) VALUES (347, "Deep Baroque");
INSERT INTO Genre (id, name) VALUES (348, "Deep Brazilian Pop");
INSERT INTO Genre (id, name) VALUES (349, "Deep Breakcore");
INSERT INTO Genre (id, name) VALUES (350, "Deep Canadian Indie");
INSERT INTO Genre (id, name) VALUES (351, "Deep Ccm");
INSERT INTO Genre (id, name) VALUES (352, "Deep Cello");
INSERT INTO Genre (id, name) VALUES (353, "Deep Chill");
INSERT INTO Genre (id, name) VALUES (354, "Deep Chill-out");
INSERT INTO Genre (id, name) VALUES (355, "Deep Christian Rock");
INSERT INTO Genre (id, name) VALUES (356, "Deep Classic Garage Rock");
INSERT INTO Genre (id, name) VALUES (357, "Deep Classical Piano");
INSERT INTO Genre (id, name) VALUES (358, "Deep Comedy");
INSERT INTO Genre (id, name) VALUES (359, "Deep Contemporary Country");
INSERT INTO Genre (id, name) VALUES (360, "Deep Dance Pop");
INSERT INTO Genre (id, name) VALUES (361, "Deep Darkpsy");
INSERT INTO Genre (id, name) VALUES (362, "Deep Deep House");
INSERT INTO Genre (id, name) VALUES (363, "Deep Deep Tech House");
INSERT INTO Genre (id, name) VALUES (364, "Deep Delta Blues");
INSERT INTO Genre (id, name) VALUES (365, "Deep Disco");
INSERT INTO Genre (id, name) VALUES (366, "Deep Disco House");
INSERT INTO Genre (id, name) VALUES (367, "Deep Discofox");
INSERT INTO Genre (id, name) VALUES (368, "Deep Downtempo Fusion");
INSERT INTO Genre (id, name) VALUES (369, "Deep Dub Techno");
INSERT INTO Genre (id, name) VALUES (370, "Deep East Coast Hip Hop");
INSERT INTO Genre (id, name) VALUES (371, "Deep Euro House");
INSERT INTO Genre (id, name) VALUES (372, "Deep Eurodance");
INSERT INTO Genre (id, name) VALUES (373, "Deep Filthstep");
INSERT INTO Genre (id, name) VALUES (374, "Deep Flow");
INSERT INTO Genre (id, name) VALUES (375, "Deep Folk Metal");
INSERT INTO Genre (id, name) VALUES (376, "Deep Free Jazz");
INSERT INTO Genre (id, name) VALUES (377, "Deep Freestyle");
INSERT INTO Genre (id, name) VALUES (378, "Deep Full On");
INSERT INTO Genre (id, name) VALUES (379, "Deep Funk");
INSERT INTO Genre (id, name) VALUES (380, "Deep Funk House");
INSERT INTO Genre (id, name) VALUES (381, "Deep G Funk");
INSERT INTO Genre (id, name) VALUES (382, "Deep German Indie");
INSERT INTO Genre (id, name) VALUES (383, "Deep German Punk");
INSERT INTO Genre (id, name) VALUES (384, "Deep Gothic Post-punk");
INSERT INTO Genre (id, name) VALUES (385, "Deep Happy Hardcore");
INSERT INTO Genre (id, name) VALUES (386, "Deep Hardcore");
INSERT INTO Genre (id, name) VALUES (387, "Deep Hardcore Punk");
INSERT INTO Genre (id, name) VALUES (388, "Deep Hardstyle");
INSERT INTO Genre (id, name) VALUES (389, "Deep House");
INSERT INTO Genre (id, name) VALUES (390, "Deep Indian Pop");
INSERT INTO Genre (id, name) VALUES (391, "Deep Indie Pop");
INSERT INTO Genre (id, name) VALUES (392, "Deep Indie Rock");
INSERT INTO Genre (id, name) VALUES (393, "Deep Indie Singer-songwriter");
INSERT INTO Genre (id, name) VALUES (394, "Deep Italo Disco");
INSERT INTO Genre (id, name) VALUES (395, "Deep Jazz Fusion");
INSERT INTO Genre (id, name) VALUES (396, "Deep Jazz Guitar");
INSERT INTO Genre (id, name) VALUES (397, "Deep Jazz Piano");
INSERT INTO Genre (id, name) VALUES (398, "Deep Latin Alternative");
INSERT INTO Genre (id, name) VALUES (399, "Deep Liquid");
INSERT INTO Genre (id, name) VALUES (400, "Deep Liquid Bass");
INSERT INTO Genre (id, name) VALUES (401, "Deep Melodic Death Metal");
INSERT INTO Genre (id, name) VALUES (402, "Deep Melodic Hard Rock");
INSERT INTO Genre (id, name) VALUES (403, "Deep Melodic House");
INSERT INTO Genre (id, name) VALUES (404, "Deep Melodic Metalcore");
INSERT INTO Genre (id, name) VALUES (405, "Deep Minimal Techno");
INSERT INTO Genre (id, name) VALUES (406, "Deep Motown");
INSERT INTO Genre (id, name) VALUES (407, "Deep Neo-synthpop");
INSERT INTO Genre (id, name) VALUES (408, "Deep Neofolk");
INSERT INTO Genre (id, name) VALUES (409, "Deep New Wave");
INSERT INTO Genre (id, name) VALUES (410, "Deep Nordic Folk");
INSERT INTO Genre (id, name) VALUES (411, "Deep Northern Soul");
INSERT INTO Genre (id, name) VALUES (412, "Deep Opera");
INSERT INTO Genre (id, name) VALUES (413, "Deep Orchestral");
INSERT INTO Genre (id, name) VALUES (414, "Deep Orgcore");
INSERT INTO Genre (id, name) VALUES (415, "Deep Pop Emo");
INSERT INTO Genre (id, name) VALUES (416, "Deep Pop Punk");
INSERT INTO Genre (id, name) VALUES (417, "Deep Power-pop Punk");
INSERT INTO Genre (id, name) VALUES (418, "Deep Progressive House");
INSERT INTO Genre (id, name) VALUES (419, "Deep Progressive Trance");
INSERT INTO Genre (id, name) VALUES (420, "Deep Psychobilly");
INSERT INTO Genre (id, name) VALUES (421, "Deep Psytrance");
INSERT INTO Genre (id, name) VALUES (422, "Deep Punk Rock");
INSERT INTO Genre (id, name) VALUES (423, "Deep Ragga");
INSERT INTO Genre (id, name) VALUES (424, "Deep Rai");
INSERT INTO Genre (id, name) VALUES (425, "Deep Regional Mexican");
INSERT INTO Genre (id, name) VALUES (426, "Deep Smooth Jazz");
INSERT INTO Genre (id, name) VALUES (427, "Deep Soft Rock");
INSERT INTO Genre (id, name) VALUES (428, "Deep Soul House");
INSERT INTO Genre (id, name) VALUES (429, "Deep Soundtrack");
INSERT INTO Genre (id, name) VALUES (430, "Deep Southern Soul");
INSERT INTO Genre (id, name) VALUES (431, "Deep Space Rock");
INSERT INTO Genre (id, name) VALUES (432, "Deep String Quartet");
INSERT INTO Genre (id, name) VALUES (433, "Deep Sunset Lounge");
INSERT INTO Genre (id, name) VALUES (434, "Deep Surf Music");
INSERT INTO Genre (id, name) VALUES (435, "Deep Symphonic Black Metal");
INSERT INTO Genre (id, name) VALUES (436, "Deep Talent Show");
INSERT INTO Genre (id, name) VALUES (437, "Deep Tech House");
INSERT INTO Genre (id, name) VALUES (438, "Deep Thrash Metal");
INSERT INTO Genre (id, name) VALUES (439, "Deep Trap");
INSERT INTO Genre (id, name) VALUES (440, "Deep Turkish Pop");
INSERT INTO Genre (id, name) VALUES (441, "Deep Uplifting Trance");
INSERT INTO Genre (id, name) VALUES (442, "Deep Vocal House");
INSERT INTO Genre (id, name) VALUES (443, "Deep Vocal Jazz");
INSERT INTO Genre (id, name) VALUES (444, "Delta Blues");
INSERT INTO Genre (id, name) VALUES (445, "Demoscene");
INSERT INTO Genre (id, name) VALUES (446, "Denver Indie");
INSERT INTO Genre (id, name) VALUES (447, "Depressive Black Metal");
INSERT INTO Genre (id, name) VALUES (448, "Desert Blues");
INSERT INTO Genre (id, name) VALUES (449, "Desi");
INSERT INTO Genre (id, name) VALUES (450, "Destroy Techno");
INSERT INTO Genre (id, name) VALUES (451, "Detroit Hip Hop");
INSERT INTO Genre (id, name) VALUES (452, "Detroit Techno");
INSERT INTO Genre (id, name) VALUES (453, "Didgeridoo");
INSERT INTO Genre (id, name) VALUES (454, "Digital Hardcore");
INSERT INTO Genre (id, name) VALUES (455, "Dirty South Rap");
INSERT INTO Genre (id, name) VALUES (456, "Dirty Texas Rap");
INSERT INTO Genre (id, name) VALUES (457, "Disco");
INSERT INTO Genre (id, name) VALUES (458, "Disco House");
INSERT INTO Genre (id, name) VALUES (459, "Discofox");
INSERT INTO Genre (id, name) VALUES (460, "Dixieland");
INSERT INTO Genre (id, name) VALUES (461, "Djent");
INSERT INTO Genre (id, name) VALUES (462, "Dominican Pop");
INSERT INTO Genre (id, name) VALUES (463, "Doo-wop");
INSERT INTO Genre (id, name) VALUES (464, "Doom Metal");
INSERT INTO Genre (id, name) VALUES (465, "Doomcore");
INSERT INTO Genre (id, name) VALUES (466, "Doujin");
INSERT INTO Genre (id, name) VALUES (467, "Downtempo");
INSERT INTO Genre (id, name) VALUES (468, "Downtempo Fusion");
INSERT INTO Genre (id, name) VALUES (469, "Downtempo Trip Hop");
INSERT INTO Genre (id, name) VALUES (470, "Drama");
INSERT INTO Genre (id, name) VALUES (471, "Dream Pop");
INSERT INTO Genre (id, name) VALUES (472, "Dreamo");
INSERT INTO Genre (id, name) VALUES (473, "Drill And Bass");
INSERT INTO Genre (id, name) VALUES (474, "Drone");
INSERT INTO Genre (id, name) VALUES (475, "Drone Folk");
INSERT INTO Genre (id, name) VALUES (476, "Drone Metal");
INSERT INTO Genre (id, name) VALUES (477, "Drone Psych");
INSERT INTO Genre (id, name) VALUES (478, "Drum And Bass");
INSERT INTO Genre (id, name) VALUES (479, "Drumfunk");
INSERT INTO Genre (id, name) VALUES (480, "Dub");
INSERT INTO Genre (id, name) VALUES (481, "Dub Techno");
INSERT INTO Genre (id, name) VALUES (482, "Dubstep");
INSERT INTO Genre (id, name) VALUES (483, "Dubstep Product");
INSERT INTO Genre (id, name) VALUES (484, "Dubsteppe");
INSERT INTO Genre (id, name) VALUES (485, "Duranguense");
INSERT INTO Genre (id, name) VALUES (486, "Dutch Hip Hop");
INSERT INTO Genre (id, name) VALUES (487, "Dutch House");
INSERT INTO Genre (id, name) VALUES (488, "Dutch Pop");
INSERT INTO Genre (id, name) VALUES (489, "Dutch Rock");
INSERT INTO Genre (id, name) VALUES (490, "E6fi");
INSERT INTO Genre (id, name) VALUES (491, "Early Music");
INSERT INTO Genre (id, name) VALUES (492, "Early Music Ensemble");
INSERT INTO Genre (id, name) VALUES (493, "East Coast Hip Hop");
INSERT INTO Genre (id, name) VALUES (494, "Easy Listening");
INSERT INTO Genre (id, name) VALUES (495, "Ebm");
INSERT INTO Genre (id, name) VALUES (496, "Ectofolk");
INSERT INTO Genre (id, name) VALUES (497, "Ecuadoria");
INSERT INTO Genre (id, name) VALUES (498, "Edm");
INSERT INTO Genre (id, name) VALUES (499, "Electric Blues");
INSERT INTO Genre (id, name) VALUES (500, "Electro");
INSERT INTO Genre (id, name) VALUES (501, "Electro Dub");
INSERT INTO Genre (id, name) VALUES (502, "Electro House");
INSERT INTO Genre (id, name) VALUES (503, "Electro Jazz");
INSERT INTO Genre (id, name) VALUES (504, "Electro Latino");
INSERT INTO Genre (id, name) VALUES (505, "Electro Swing");
INSERT INTO Genre (id, name) VALUES (506, "Electro Trash");
INSERT INTO Genre (id, name) VALUES (507, "Electro-industrial");
INSERT INTO Genre (id, name) VALUES (508, "Electroacoustic Improvisation");
INSERT INTO Genre (id, name) VALUES (509, "Electroclash");
INSERT INTO Genre (id, name) VALUES (510, "Electrofox");
INSERT INTO Genre (id, name) VALUES (511, "Electronic");
INSERT INTO Genre (id, name) VALUES (512, "Electronica");
INSERT INTO Genre (id, name) VALUES (513, "Electronicore");
INSERT INTO Genre (id, name) VALUES (514, "Electropowerpop");
INSERT INTO Genre (id, name) VALUES (515, "Electropunk");
INSERT INTO Genre (id, name) VALUES (516, "Emo");
INSERT INTO Genre (id, name) VALUES (517, "Emo Punk");
INSERT INTO Genre (id, name) VALUES (518, "Enka");
INSERT INTO Genre (id, name) VALUES (519, "Entehno");
INSERT INTO Genre (id, name) VALUES (520, "Environmental");
INSERT INTO Genre (id, name) VALUES (521, "Epicore");
INSERT INTO Genre (id, name) VALUES (522, "Estonian Pop");
INSERT INTO Genre (id, name) VALUES (523, "Ethereal Gothic");
INSERT INTO Genre (id, name) VALUES (524, "Ethereal Wave");
INSERT INTO Genre (id, name) VALUES (525, "Etherpop");
INSERT INTO Genre (id, name) VALUES (526, "Ethiopian Pop");
INSERT INTO Genre (id, name) VALUES (527, "Eurobeat");
INSERT INTO Genre (id, name) VALUES (528, "Eurodance");
INSERT INTO Genre (id, name) VALUES (529, "Europop");
INSERT INTO Genre (id, name) VALUES (530, "Euroska");
INSERT INTO Genre (id, name) VALUES (531, "Eurovision");
INSERT INTO Genre (id, name) VALUES (532, "Exotica");
INSERT INTO Genre (id, name) VALUES (533, "Experimental");
INSERT INTO Genre (id, name) VALUES (534, "Experimental Dubstep");
INSERT INTO Genre (id, name) VALUES (535, "Experimental Psych");
INSERT INTO Genre (id, name) VALUES (536, "Experimental Rock");
INSERT INTO Genre (id, name) VALUES (537, "Fado");
INSERT INTO Genre (id, name) VALUES (538, "Fake");
INSERT INTO Genre (id, name) VALUES (539, "Fallen Angel");
INSERT INTO Genre (id, name) VALUES (540, "Faroese Pop");
INSERT INTO Genre (id, name) VALUES (541, "Fast Melodic Punk");
INSERT INTO Genre (id, name) VALUES (542, "Fidget House");
INSERT INTO Genre (id, name) VALUES (543, "Filmi");
INSERT INTO Genre (id, name) VALUES (544, "Filter House");
INSERT INTO Genre (id, name) VALUES (545, "Filthstep");
INSERT INTO Genre (id, name) VALUES (546, "Fingerstyle");
INSERT INTO Genre (id, name) VALUES (547, "Finnish Hardcore");
INSERT INTO Genre (id, name) VALUES (548, "Finnish Hip Hop");
INSERT INTO Genre (id, name) VALUES (549, "Finnish Indie");
INSERT INTO Genre (id, name) VALUES (550, "Finnish Jazz");
INSERT INTO Genre (id, name) VALUES (551, "Finnish Metal");
INSERT INTO Genre (id, name) VALUES (552, "Finnish Pop");
INSERT INTO Genre (id, name) VALUES (553, "Flamenco");
INSERT INTO Genre (id, name) VALUES (554, "Flick Hop");
INSERT INTO Genre (id, name) VALUES (555, "Folk");
INSERT INTO Genre (id, name) VALUES (556, "Folk Christmas");
INSERT INTO Genre (id, name) VALUES (557, "Folk Metal");
INSERT INTO Genre (id, name) VALUES (558, "Folk Punk");
INSERT INTO Genre (id, name) VALUES (559, "Folk Rock");
INSERT INTO Genre (id, name) VALUES (560, "Folk-pop");
INSERT INTO Genre (id, name) VALUES (561, "Folk-prog");
INSERT INTO Genre (id, name) VALUES (562, "Folklore Argentino");
INSERT INTO Genre (id, name) VALUES (563, "Folkmusik");
INSERT INTO Genre (id, name) VALUES (564, "Footwork");
INSERT INTO Genre (id, name) VALUES (565, "Forro");
INSERT INTO Genre (id, name) VALUES (566, "Fourth World");
INSERT INTO Genre (id, name) VALUES (567, "Freak Folk");
INSERT INTO Genre (id, name) VALUES (568, "Freakbeat");
INSERT INTO Genre (id, name) VALUES (569, "Free Improvisation");
INSERT INTO Genre (id, name) VALUES (570, "Free Jazz");
INSERT INTO Genre (id, name) VALUES (571, "Freestyle");
INSERT INTO Genre (id, name) VALUES (572, "French Folk");
INSERT INTO Genre (id, name) VALUES (573, "French Folk Pop");
INSERT INTO Genre (id, name) VALUES (574, "French Hip Hop");
INSERT INTO Genre (id, name) VALUES (575, "French Indie Pop");
INSERT INTO Genre (id, name) VALUES (576, "French Movie Tunes");
INSERT INTO Genre (id, name) VALUES (577, "French Pop");
INSERT INTO Genre (id, name) VALUES (578, "French Punk");
INSERT INTO Genre (id, name) VALUES (579, "French Reggae");
INSERT INTO Genre (id, name) VALUES (580, "French Rock");
INSERT INTO Genre (id, name) VALUES (581, "Full On");
INSERT INTO Genre (id, name) VALUES (582, "Funeral Doom");
INSERT INTO Genre (id, name) VALUES (583, "Funk");
INSERT INTO Genre (id, name) VALUES (584, "Funk Carioca");
INSERT INTO Genre (id, name) VALUES (585, "Funk Metal");
INSERT INTO Genre (id, name) VALUES (586, "Funk Rock");
INSERT INTO Genre (id, name) VALUES (587, "Funky Breaks");
INSERT INTO Genre (id, name) VALUES (588, "Future Ambient");
INSERT INTO Genre (id, name) VALUES (589, "Future Garage");
INSERT INTO Genre (id, name) VALUES (590, "Futurepop");
INSERT INTO Genre (id, name) VALUES (591, "G Funk");
INSERT INTO Genre (id, name) VALUES (592, "Gabba");
INSERT INTO Genre (id, name) VALUES (593, "Galego");
INSERT INTO Genre (id, name) VALUES (594, "Gamecore");
INSERT INTO Genre (id, name) VALUES (595, "Gamelan");
INSERT INTO Genre (id, name) VALUES (596, "Gangster Rap");
INSERT INTO Genre (id, name) VALUES (597, "Garage Pop");
INSERT INTO Genre (id, name) VALUES (598, "Garage Punk");
INSERT INTO Genre (id, name) VALUES (599, "Garage Punk Blues");
INSERT INTO Genre (id, name) VALUES (600, "Garage Rock");
INSERT INTO Genre (id, name) VALUES (601, "Gauze Pop");
INSERT INTO Genre (id, name) VALUES (602, "Gbvfi");
INSERT INTO Genre (id, name) VALUES (603, "Geek Folk");
INSERT INTO Genre (id, name) VALUES (604, "Geek Rock");
INSERT INTO Genre (id, name) VALUES (605, "German Ccm");
INSERT INTO Genre (id, name) VALUES (606, "German Hip Hop");
INSERT INTO Genre (id, name) VALUES (607, "German Indie");
INSERT INTO Genre (id, name) VALUES (608, "German Metal");
INSERT INTO Genre (id, name) VALUES (609, "German Oi");
INSERT INTO Genre (id, name) VALUES (610, "German Pop");
INSERT INTO Genre (id, name) VALUES (611, "German Pop Rock");
INSERT INTO Genre (id, name) VALUES (612, "German Punk");
INSERT INTO Genre (id, name) VALUES (613, "German Show Tunes");
INSERT INTO Genre (id, name) VALUES (614, "German Techno");
INSERT INTO Genre (id, name) VALUES (615, "Ghettotech");
INSERT INTO Genre (id, name) VALUES (616, "Ghoststep");
INSERT INTO Genre (id, name) VALUES (617, "Girl Group");
INSERT INTO Genre (id, name) VALUES (618, "Glam Metal");
INSERT INTO Genre (id, name) VALUES (619, "Glam Rock");
INSERT INTO Genre (id, name) VALUES (620, "Glitch");
INSERT INTO Genre (id, name) VALUES (621, "Glitch Beats");
INSERT INTO Genre (id, name) VALUES (622, "Glitch Hop");
INSERT INTO Genre (id, name) VALUES (623, "Glitter Trance");
INSERT INTO Genre (id, name) VALUES (624, "Goa Trance");
INSERT INTO Genre (id, name) VALUES (625, "Goregrind");
INSERT INTO Genre (id, name) VALUES (626, "Gospel");
INSERT INTO Genre (id, name) VALUES (627, "Gospel Blues");
INSERT INTO Genre (id, name) VALUES (628, "Gospel Reggae");
INSERT INTO Genre (id, name) VALUES (629, "Gothic Alternative");
INSERT INTO Genre (id, name) VALUES (630, "Gothic Americana");
INSERT INTO Genre (id, name) VALUES (631, "Gothic Doom");
INSERT INTO Genre (id, name) VALUES (632, "Gothic Metal");
INSERT INTO Genre (id, name) VALUES (633, "Gothic Post-punk");
INSERT INTO Genre (id, name) VALUES (634, "Gothic Rock");
INSERT INTO Genre (id, name) VALUES (635, "Gothic Symphonic Metal");
INSERT INTO Genre (id, name) VALUES (636, "Grave Wave");
INSERT INTO Genre (id, name) VALUES (637, "Greek Hip Hop");
INSERT INTO Genre (id, name) VALUES (638, "Greek House");
INSERT INTO Genre (id, name) VALUES (639, "Greek Indie");
INSERT INTO Genre (id, name) VALUES (640, "Grim Death Metal");
INSERT INTO Genre (id, name) VALUES (641, "Grime");
INSERT INTO Genre (id, name) VALUES (642, "Grindcore");
INSERT INTO Genre (id, name) VALUES (643, "Grisly Death Metal");
INSERT INTO Genre (id, name) VALUES (644, "Groove Metal");
INSERT INTO Genre (id, name) VALUES (645, "Grunge");
INSERT INTO Genre (id, name) VALUES (646, "Grunge Pop");
INSERT INTO Genre (id, name) VALUES (647, "Grupera");
INSERT INTO Genre (id, name) VALUES (648, "Guidance");
INSERT INTO Genre (id, name) VALUES (649, "Gypsy Jazz");
INSERT INTO Genre (id, name) VALUES (650, "Hands Up");
INSERT INTO Genre (id, name) VALUES (651, "Happy Hardcore");
INSERT INTO Genre (id, name) VALUES (652, "Hard Alternative");
INSERT INTO Genre (id, name) VALUES (653, "Hard Bop");
INSERT INTO Genre (id, name) VALUES (654, "Hard Glam");
INSERT INTO Genre (id, name) VALUES (655, "Hard House");
INSERT INTO Genre (id, name) VALUES (656, "Hard Rock");
INSERT INTO Genre (id, name) VALUES (657, "Hard Stoner Rock");
INSERT INTO Genre (id, name) VALUES (658, "Hard Trance");
INSERT INTO Genre (id, name) VALUES (659, "Hardcore");
INSERT INTO Genre (id, name) VALUES (660, "Hardcore Breaks");
INSERT INTO Genre (id, name) VALUES (661, "Hardcore Hip Hop");
INSERT INTO Genre (id, name) VALUES (662, "Hardcore Punk");
INSERT INTO Genre (id, name) VALUES (663, "Hardcore Techno");
INSERT INTO Genre (id, name) VALUES (664, "Hardstyle");
INSERT INTO Genre (id, name) VALUES (665, "Harmonica Blues");
INSERT INTO Genre (id, name) VALUES (666, "Harp");
INSERT INTO Genre (id, name) VALUES (667, "Hatecore");
INSERT INTO Genre (id, name) VALUES (668, "Hauntology");
INSERT INTO Genre (id, name) VALUES (669, "Hawaiian");
INSERT INTO Genre (id, name) VALUES (670, "Healing");
INSERT INTO Genre (id, name) VALUES (671, "Heavy Alternative");
INSERT INTO Genre (id, name) VALUES (672, "Heavy Christmas");
INSERT INTO Genre (id, name) VALUES (673, "Heavy Gothic Rock");
INSERT INTO Genre (id, name) VALUES (674, "Hi Nrg");
INSERT INTO Genre (id, name) VALUES (675, "Highlife");
INSERT INTO Genre (id, name) VALUES (676, "Hindustani Classical");
INSERT INTO Genre (id, name) VALUES (677, "Hip Hop");
INSERT INTO Genre (id, name) VALUES (678, "Hip Hop Quebecois");
INSERT INTO Genre (id, name) VALUES (679, "Hip Hop Tuga");
INSERT INTO Genre (id, name) VALUES (680, "Hip House");
INSERT INTO Genre (id, name) VALUES (681, "Hip Pop");
INSERT INTO Genre (id, name) VALUES (682, "Hiplife");
INSERT INTO Genre (id, name) VALUES (683, "Hoerspiel");
INSERT INTO Genre (id, name) VALUES (684, "Hollywood");
INSERT INTO Genre (id, name) VALUES (685, "Honky Tonk");
INSERT INTO Genre (id, name) VALUES (686, "Horror Punk");
INSERT INTO Genre (id, name) VALUES (687, "Horrorcore");
INSERT INTO Genre (id, name) VALUES (688, "House");
INSERT INTO Genre (id, name) VALUES (689, "Hungarian Hip Hop");
INSERT INTO Genre (id, name) VALUES (690, "Hungarian Pop");
INSERT INTO Genre (id, name) VALUES (691, "Hungarian Rock");
INSERT INTO Genre (id, name) VALUES (692, "Hurban");
INSERT INTO Genre (id, name) VALUES (693, "Hyphy");
INSERT INTO Genre (id, name) VALUES (694, "Icelandic Pop");
INSERT INTO Genre (id, name) VALUES (695, "Idol");
INSERT INTO Genre (id, name) VALUES (696, "Illbient");
INSERT INTO Genre (id, name) VALUES (697, "Indian Classical");
INSERT INTO Genre (id, name) VALUES (698, "Indian Pop");
INSERT INTO Genre (id, name) VALUES (699, "Indian Rock");
INSERT INTO Genre (id, name) VALUES (700, "Indie Christmas");
INSERT INTO Genre (id, name) VALUES (701, "Indie Dream Pop");
INSERT INTO Genre (id, name) VALUES (702, "Indie Emo");
INSERT INTO Genre (id, name) VALUES (703, "Indie Emo Rock");
INSERT INTO Genre (id, name) VALUES (704, "Indie Folk");
INSERT INTO Genre (id, name) VALUES (705, "Indie Fuzzpop");
INSERT INTO Genre (id, name) VALUES (706, "Indie Pop");
INSERT INTO Genre (id, name) VALUES (707, "Indie Pop Rock");
INSERT INTO Genre (id, name) VALUES (708, "Indie Post-punk");
INSERT INTO Genre (id, name) VALUES (709, "Indie Psych-pop");
INSERT INTO Genre (id, name) VALUES (710, "Indie R&b");
INSERT INTO Genre (id, name) VALUES (711, "Indie Rock");
INSERT INTO Genre (id, name) VALUES (712, "Indie Shoegaze");
INSERT INTO Genre (id, name) VALUES (713, "Indie Singer-songwriter");
INSERT INTO Genre (id, name) VALUES (714, "Indietronica");
INSERT INTO Genre (id, name) VALUES (715, "Indonesian Indie");
INSERT INTO Genre (id, name) VALUES (716, "Indonesian Pop");
INSERT INTO Genre (id, name) VALUES (717, "Indorock");
INSERT INTO Genre (id, name) VALUES (718, "Industrial");
INSERT INTO Genre (id, name) VALUES (719, "Industrial Metal");
INSERT INTO Genre (id, name) VALUES (720, "Industrial Rock");
INSERT INTO Genre (id, name) VALUES (721, "Instrumental Post Rock");
INSERT INTO Genre (id, name) VALUES (722, "Intelligent Dance Music");
INSERT INTO Genre (id, name) VALUES (723, "Irish Folk");
INSERT INTO Genre (id, name) VALUES (724, "Irish Indie");
INSERT INTO Genre (id, name) VALUES (725, "Irish Rock");
INSERT INTO Genre (id, name) VALUES (726, "Iskelma");
INSERT INTO Genre (id, name) VALUES (727, "Islamic Recitation");
INSERT INTO Genre (id, name) VALUES (728, "Israeli Rock");
INSERT INTO Genre (id, name) VALUES (729, "Italian Disco");
INSERT INTO Genre (id, name) VALUES (730, "Italian Folk");
INSERT INTO Genre (id, name) VALUES (731, "Italian Hip Hop");
INSERT INTO Genre (id, name) VALUES (732, "Italian Indie Pop");
INSERT INTO Genre (id, name) VALUES (733, "Italian Jazz");
INSERT INTO Genre (id, name) VALUES (734, "Italian Pop");
INSERT INTO Genre (id, name) VALUES (735, "Italian Pop Rock");
INSERT INTO Genre (id, name) VALUES (736, "Italian Progressive Rock");
INSERT INTO Genre (id, name) VALUES (737, "Italian Punk");
INSERT INTO Genre (id, name) VALUES (738, "Italo Dance");
INSERT INTO Genre (id, name) VALUES (739, "J-alt");
INSERT INTO Genre (id, name) VALUES (740, "J-ambient");
INSERT INTO Genre (id, name) VALUES (741, "J-core");
INSERT INTO Genre (id, name) VALUES (742, "J-dance");
INSERT INTO Genre (id, name) VALUES (743, "J-idol");
INSERT INTO Genre (id, name) VALUES (744, "J-indie");
INSERT INTO Genre (id, name) VALUES (745, "J-metal");
INSERT INTO Genre (id, name) VALUES (746, "J-pop");
INSERT INTO Genre (id, name) VALUES (747, "J-poppunk");
INSERT INTO Genre (id, name) VALUES (748, "J-poprock");
INSERT INTO Genre (id, name) VALUES (749, "J-punk");
INSERT INTO Genre (id, name) VALUES (750, "J-rap");
INSERT INTO Genre (id, name) VALUES (751, "J-rock");
INSERT INTO Genre (id, name) VALUES (752, "J-theme");
INSERT INTO Genre (id, name) VALUES (753, "Jam Band");
INSERT INTO Genre (id, name) VALUES (754, "Jangle Pop");
INSERT INTO Genre (id, name) VALUES (755, "Jangle Rock");
INSERT INTO Genre (id, name) VALUES (756, "Japanese Jazztronica");
INSERT INTO Genre (id, name) VALUES (757, "Japanese Psychedelic");
INSERT INTO Genre (id, name) VALUES (758, "Japanese R&b");
INSERT INTO Genre (id, name) VALUES (759, "Japanese Standards");
INSERT INTO Genre (id, name) VALUES (760, "Japanese Traditional");
INSERT INTO Genre (id, name) VALUES (761, "Japanoise");
INSERT INTO Genre (id, name) VALUES (762, "Jazz");
INSERT INTO Genre (id, name) VALUES (763, "Jazz Bass");
INSERT INTO Genre (id, name) VALUES (764, "Jazz Blues");
INSERT INTO Genre (id, name) VALUES (765, "Jazz Brass");
INSERT INTO Genre (id, name) VALUES (766, "Jazz Christmas");
INSERT INTO Genre (id, name) VALUES (767, "Jazz Funk");
INSERT INTO Genre (id, name) VALUES (768, "Jazz Fusion");
INSERT INTO Genre (id, name) VALUES (769, "Jazz Metal");
INSERT INTO Genre (id, name) VALUES (770, "Jazz Orchestra");
INSERT INTO Genre (id, name) VALUES (771, "Jazz Trio");
INSERT INTO Genre (id, name) VALUES (772, "Jerk");
INSERT INTO Genre (id, name) VALUES (773, "Jig And Reel");
INSERT INTO Genre (id, name) VALUES (774, "Judaica");
INSERT INTO Genre (id, name) VALUES (775, "Jug Band");
INSERT INTO Genre (id, name) VALUES (776, "Juggalo");
INSERT INTO Genre (id, name) VALUES (777, "Jump Blues");
INSERT INTO Genre (id, name) VALUES (778, "Jump Up");
INSERT INTO Genre (id, name) VALUES (779, "Jumpstyle");
INSERT INTO Genre (id, name) VALUES (780, "Jungle");
INSERT INTO Genre (id, name) VALUES (781, "K-hop");
INSERT INTO Genre (id, name) VALUES (782, "K-indie");
INSERT INTO Genre (id, name) VALUES (783, "K-pop");
INSERT INTO Genre (id, name) VALUES (784, "K-rock");
INSERT INTO Genre (id, name) VALUES (785, "Kabarett");
INSERT INTO Genre (id, name) VALUES (786, "Karneval");
INSERT INTO Genre (id, name) VALUES (787, "Kc Indie");
INSERT INTO Genre (id, name) VALUES (788, "Kindermusik");
INSERT INTO Genre (id, name) VALUES (789, "Kirtan");
INSERT INTO Genre (id, name) VALUES (790, "Kiwi Rock");
INSERT INTO Genre (id, name) VALUES (791, "Kizomba");
INSERT INTO Genre (id, name) VALUES (792, "Klapa");
INSERT INTO Genre (id, name) VALUES (793, "Klezmer");
INSERT INTO Genre (id, name) VALUES (794, "Kompa");
INSERT INTO Genre (id, name) VALUES (795, "Kraut Rock");
INSERT INTO Genre (id, name) VALUES (796, "Kuduro");
INSERT INTO Genre (id, name) VALUES (797, "Kurdish Folk");
INSERT INTO Genre (id, name) VALUES (798, "Kwaito");
INSERT INTO Genre (id, name) VALUES (799, "La Indie");
INSERT INTO Genre (id, name) VALUES (800, "Laboratorio");
INSERT INTO Genre (id, name) VALUES (801, "Laiko");
INSERT INTO Genre (id, name) VALUES (802, "Latin");
INSERT INTO Genre (id, name) VALUES (803, "Latin Alternative");
INSERT INTO Genre (id, name) VALUES (804, "Latin Christian");
INSERT INTO Genre (id, name) VALUES (805, "Latin Christmas");
INSERT INTO Genre (id, name) VALUES (806, "Latin Electronica");
INSERT INTO Genre (id, name) VALUES (807, "Latin Hip Hop");
INSERT INTO Genre (id, name) VALUES (808, "Latin Jazz");
INSERT INTO Genre (id, name) VALUES (809, "Latin Metal");
INSERT INTO Genre (id, name) VALUES (810, "Latin Pop");
INSERT INTO Genre (id, name) VALUES (811, "Latvian Pop");
INSERT INTO Genre (id, name) VALUES (812, "Lds");
INSERT INTO Genre (id, name) VALUES (813, "Leeds Indie");
INSERT INTO Genre (id, name) VALUES (814, "Levenslied");
INSERT INTO Genre (id, name) VALUES (815, "Liedermacher");
INSERT INTO Genre (id, name) VALUES (816, "Light Music");
INSERT INTO Genre (id, name) VALUES (817, "Lilith");
INSERT INTO Genre (id, name) VALUES (818, "Liquid Funk");
INSERT INTO Genre (id, name) VALUES (819, "Lithumania");
INSERT INTO Genre (id, name) VALUES (820, "Liturgical");
INSERT INTO Genre (id, name) VALUES (821, "Lo Star");
INSERT INTO Genre (id, name) VALUES (822, "Lo-fi");
INSERT INTO Genre (id, name) VALUES (823, "Louisiana Blues");
INSERT INTO Genre (id, name) VALUES (824, "Louisville Indie");
INSERT INTO Genre (id, name) VALUES (825, "Lounge");
INSERT INTO Genre (id, name) VALUES (826, "Lounge House");
INSERT INTO Genre (id, name) VALUES (827, "Lovers Rock");
INSERT INTO Genre (id, name) VALUES (828, "Lowercase");
INSERT INTO Genre (id, name) VALUES (829, "Luk Thung");
INSERT INTO Genre (id, name) VALUES (830, "Madchester");
INSERT INTO Genre (id, name) VALUES (831, "Maghreb");
INSERT INTO Genre (id, name) VALUES (832, "Magyar");
INSERT INTO Genre (id, name) VALUES (833, "Makossa");
INSERT INTO Genre (id, name) VALUES (834, "Malagasy Folk");
INSERT INTO Genre (id, name) VALUES (835, "Malaysian Pop");
INSERT INTO Genre (id, name) VALUES (836, "Mallet");
INSERT INTO Genre (id, name) VALUES (837, "Mambo");
INSERT INTO Genre (id, name) VALUES (838, "Mande Pop");
INSERT INTO Genre (id, name) VALUES (839, "Mandopop");
INSERT INTO Genre (id, name) VALUES (840, "Manele");
INSERT INTO Genre (id, name) VALUES (841, "Marching Band");
INSERT INTO Genre (id, name) VALUES (842, "Mariachi");
INSERT INTO Genre (id, name) VALUES (843, "Martial Industrial");
INSERT INTO Genre (id, name) VALUES (844, "Mashup");
INSERT INTO Genre (id, name) VALUES (845, "Math Pop");
INSERT INTO Genre (id, name) VALUES (846, "Math Rock");
INSERT INTO Genre (id, name) VALUES (847, "Mathcore");
INSERT INTO Genre (id, name) VALUES (848, "Mbalax");
INSERT INTO Genre (id, name) VALUES (849, "Medieval");
INSERT INTO Genre (id, name) VALUES (850, "Medieval Rock");
INSERT INTO Genre (id, name) VALUES (851, "Meditation");
INSERT INTO Genre (id, name) VALUES (852, "Melancholia");
INSERT INTO Genre (id, name) VALUES (853, "Melbourne Bounce");
INSERT INTO Genre (id, name) VALUES (854, "Mellow Gold");
INSERT INTO Genre (id, name) VALUES (855, "Melodic Death Metal");
INSERT INTO Genre (id, name) VALUES (856, "Melodic Hard Rock");
INSERT INTO Genre (id, name) VALUES (857, "Melodic Hardcore");
INSERT INTO Genre (id, name) VALUES (858, "Melodic Metalcore");
INSERT INTO Genre (id, name) VALUES (859, "Melodic Power Metal");
INSERT INTO Genre (id, name) VALUES (860, "Melodic Progressive Metal");
INSERT INTO Genre (id, name) VALUES (861, "Memphis Blues");
INSERT INTO Genre (id, name) VALUES (862, "Memphis Hip Hop");
INSERT INTO Genre (id, name) VALUES (863, "Memphis Soul");
INSERT INTO Genre (id, name) VALUES (864, "Merengue");
INSERT INTO Genre (id, name) VALUES (865, "Merengue Urbano");
INSERT INTO Genre (id, name) VALUES (866, "Merseybeat");
INSERT INTO Genre (id, name) VALUES (867, "Metal");
INSERT INTO Genre (id, name) VALUES (868, "Metalcore");
INSERT INTO Genre (id, name) VALUES (869, "Metropopolis");
INSERT INTO Genre (id, name) VALUES (870, "Mexican Indie");
INSERT INTO Genre (id, name) VALUES (871, "Mexican Rock-and-roll");
INSERT INTO Genre (id, name) VALUES (872, "Mexican Son");
INSERT INTO Genre (id, name) VALUES (873, "Mexican Traditional");
INSERT INTO Genre (id, name) VALUES (874, "Miami Bass");
INSERT INTO Genre (id, name) VALUES (875, "Michigan Indie");
INSERT INTO Genre (id, name) VALUES (876, "Microhouse");
INSERT INTO Genre (id, name) VALUES (877, "Military Band");
INSERT INTO Genre (id, name) VALUES (878, "Minimal");
INSERT INTO Genre (id, name) VALUES (879, "Minimal Dub");
INSERT INTO Genre (id, name) VALUES (880, "Minimal Dubstep");
INSERT INTO Genre (id, name) VALUES (881, "Minimal Melodic Techno");
INSERT INTO Genre (id, name) VALUES (882, "Minimal Tech House");
INSERT INTO Genre (id, name) VALUES (883, "Minimal Techno");
INSERT INTO Genre (id, name) VALUES (884, "Minimal Wave");
INSERT INTO Genre (id, name) VALUES (885, "Mizrahi");
INSERT INTO Genre (id, name) VALUES (886, "Mod Revival");
INSERT INTO Genre (id, name) VALUES (887, "Modern Blues");
INSERT INTO Genre (id, name) VALUES (888, "Modern Classical");
INSERT INTO Genre (id, name) VALUES (889, "Modern Country Rock");
INSERT INTO Genre (id, name) VALUES (890, "Modern Downshift");
INSERT INTO Genre (id, name) VALUES (891, "Modern Free Jazz");
INSERT INTO Genre (id, name) VALUES (892, "Modern Performance");
INSERT INTO Genre (id, name) VALUES (893, "Modern Southern Rock");
INSERT INTO Genre (id, name) VALUES (894, "Modern Uplift");
INSERT INTO Genre (id, name) VALUES (895, "Monastic");
INSERT INTO Genre (id, name) VALUES (896, "Moombahton");
INSERT INTO Genre (id, name) VALUES (897, "Morna");
INSERT INTO Genre (id, name) VALUES (898, "Motivation");
INSERT INTO Genre (id, name) VALUES (899, "Motown");
INSERT INTO Genre (id, name) VALUES (900, "Movie Tunes");
INSERT INTO Genre (id, name) VALUES (901, "Mpb");
INSERT INTO Genre (id, name) VALUES (902, "Musica Para Ninos");
INSERT INTO Genre (id, name) VALUES (903, "Musiikkia Lapsille");
INSERT INTO Genre (id, name) VALUES (904, "Musique Concrete");
INSERT INTO Genre (id, name) VALUES (905, "Musique Pour Enfants");
INSERT INTO Genre (id, name) VALUES (906, "Muziek Voor Kinderen");
INSERT INTO Genre (id, name) VALUES (907, "Nasheed");
INSERT INTO Genre (id, name) VALUES (908, "Nashville Sound");
INSERT INTO Genre (id, name) VALUES (909, "Native American");
INSERT INTO Genre (id, name) VALUES (910, "Necrogrind");
INSERT INTO Genre (id, name) VALUES (911, "Neo Classical Metal");
INSERT INTO Genre (id, name) VALUES (912, "Neo Honky Tonk");
INSERT INTO Genre (id, name) VALUES (913, "Neo Mellow");
INSERT INTO Genre (id, name) VALUES (914, "Neo Metal");
INSERT INTO Genre (id, name) VALUES (915, "Neo Soul");
INSERT INTO Genre (id, name) VALUES (916, "Neo Soul-jazz");
INSERT INTO Genre (id, name) VALUES (917, "Neo-industrial Rock");
INSERT INTO Genre (id, name) VALUES (918, "Neo-pagan");
INSERT INTO Genre (id, name) VALUES (919, "Neo-progressive");
INSERT INTO Genre (id, name) VALUES (920, "Neo-psychedelic");
INSERT INTO Genre (id, name) VALUES (921, "Neo-rockabilly");
INSERT INTO Genre (id, name) VALUES (922, "Neo-singer-songwriter");
INSERT INTO Genre (id, name) VALUES (923, "Neo-synthpop");
INSERT INTO Genre (id, name) VALUES (924, "Neo-trad Metal");
INSERT INTO Genre (id, name) VALUES (925, "Neo-traditional Country");
INSERT INTO Genre (id, name) VALUES (926, "Neoclassical");
INSERT INTO Genre (id, name) VALUES (927, "Neofolk");
INSERT INTO Genre (id, name) VALUES (928, "Nepali");
INSERT INTO Genre (id, name) VALUES (929, "Nerdcore");
INSERT INTO Genre (id, name) VALUES (930, "Neue Deutsche Harte");
INSERT INTO Genre (id, name) VALUES (931, "Neue Deutsche Welle");
INSERT INTO Genre (id, name) VALUES (932, "Neurofunk");
INSERT INTO Genre (id, name) VALUES (933, "Neurostep");
INSERT INTO Genre (id, name) VALUES (934, "New Age");
INSERT INTO Genre (id, name) VALUES (935, "New Age Piano");
INSERT INTO Genre (id, name) VALUES (936, "New Americana");
INSERT INTO Genre (id, name) VALUES (937, "New Beat");
INSERT INTO Genre (id, name) VALUES (938, "New Jack Smooth");
INSERT INTO Genre (id, name) VALUES (939, "New Jack Swing");
INSERT INTO Genre (id, name) VALUES (940, "New Orleans Blues");
INSERT INTO Genre (id, name) VALUES (941, "New Orleans Jazz");
INSERT INTO Genre (id, name) VALUES (942, "New Rave");
INSERT INTO Genre (id, name) VALUES (943, "New Romantic");
INSERT INTO Genre (id, name) VALUES (944, "New Tribe");
INSERT INTO Genre (id, name) VALUES (945, "New Wave");
INSERT INTO Genre (id, name) VALUES (946, "New Wave Pop");
INSERT INTO Genre (id, name) VALUES (947, "New Weird America");
INSERT INTO Genre (id, name) VALUES (948, "Ninja");
INSERT INTO Genre (id, name) VALUES (949, "Nintendocore");
INSERT INTO Genre (id, name) VALUES (950, "Nl Folk");
INSERT INTO Genre (id, name) VALUES (951, "No Wave");
INSERT INTO Genre (id, name) VALUES (952, "Noise");
INSERT INTO Genre (id, name) VALUES (953, "Noise Pop");
INSERT INTO Genre (id, name) VALUES (954, "Noise Punk");
INSERT INTO Genre (id, name) VALUES (955, "Noise Rock");
INSERT INTO Genre (id, name) VALUES (956, "Nordic Folk");
INSERT INTO Genre (id, name) VALUES (957, "Nordic House");
INSERT INTO Genre (id, name) VALUES (958, "Norteno");
INSERT INTO Genre (id, name) VALUES (959, "Northern Irish Indie");
INSERT INTO Genre (id, name) VALUES (960, "Northern Soul");
INSERT INTO Genre (id, name) VALUES (961, "Norwegian Gospel");
INSERT INTO Genre (id, name) VALUES (962, "Norwegian Hip Hop");
INSERT INTO Genre (id, name) VALUES (963, "Norwegian Jazz");
INSERT INTO Genre (id, name) VALUES (964, "Norwegian Metal");
INSERT INTO Genre (id, name) VALUES (965, "Norwegian Pop");
INSERT INTO Genre (id, name) VALUES (966, "Norwegian Punk");
INSERT INTO Genre (id, name) VALUES (967, "Norwegian Rock");
INSERT INTO Genre (id, name) VALUES (968, "Nu Age");
INSERT INTO Genre (id, name) VALUES (969, "Nu Disco");
INSERT INTO Genre (id, name) VALUES (970, "Nu Electro");
INSERT INTO Genre (id, name) VALUES (971, "Nu Gaze");
INSERT INTO Genre (id, name) VALUES (972, "Nu Jazz");
INSERT INTO Genre (id, name) VALUES (973, "Nu Metal");
INSERT INTO Genre (id, name) VALUES (974, "Nu Skool Breaks");
INSERT INTO Genre (id, name) VALUES (975, "Nu-cumbia");
INSERT INTO Genre (id, name) VALUES (976, "Nueva Cancion");
INSERT INTO Genre (id, name) VALUES (977, "Nursery");
INSERT INTO Genre (id, name) VALUES (978, "Nwobhm");
INSERT INTO Genre (id, name) VALUES (979, "Nwothm");
INSERT INTO Genre (id, name) VALUES (980, "Nz Indie");
INSERT INTO Genre (id, name) VALUES (981, "Oi");
INSERT INTO Genre (id, name) VALUES (982, "Old School Hip Hop");
INSERT INTO Genre (id, name) VALUES (983, "Old-time");
INSERT INTO Genre (id, name) VALUES (984, "Opera");
INSERT INTO Genre (id, name) VALUES (985, "Operatic Pop");
INSERT INTO Genre (id, name) VALUES (986, "Opm");
INSERT INTO Genre (id, name) VALUES (987, "Oratory");
INSERT INTO Genre (id, name) VALUES (988, "Orchestral");
INSERT INTO Genre (id, name) VALUES (989, "Organic Ambient");
INSERT INTO Genre (id, name) VALUES (990, "Orgcore");
INSERT INTO Genre (id, name) VALUES (991, "Orquesta Tipica");
INSERT INTO Genre (id, name) VALUES (992, "Orquesta Tropical");
INSERT INTO Genre (id, name) VALUES (993, "Oshare Kei");
INSERT INTO Genre (id, name) VALUES (994, "Ostrock");
INSERT INTO Genre (id, name) VALUES (995, "Outer Hip Hop");
INSERT INTO Genre (id, name) VALUES (996, "Outlaw Country");
INSERT INTO Genre (id, name) VALUES (997, "Outsider");
INSERT INTO Genre (id, name) VALUES (998, "Outsider House");
INSERT INTO Genre (id, name) VALUES (999, "P Funk");
INSERT INTO Genre (id, name) VALUES (1000, "Pagan Black Metal");
INSERT INTO Genre (id, name) VALUES (1001, "Pagode");
INSERT INTO Genre (id, name) VALUES (1002, "Pakistani Pop");
INSERT INTO Genre (id, name) VALUES (1003, "Permanent Wave");
INSERT INTO Genre (id, name) VALUES (1004, "Persian Pop");
INSERT INTO Genre (id, name) VALUES (1005, "Persian Traditional");
INSERT INTO Genre (id, name) VALUES (1006, "Perth Indie");
INSERT INTO Genre (id, name) VALUES (1007, "Peruvian Rock");
INSERT INTO Genre (id, name) VALUES (1008, "Piano Blues");
INSERT INTO Genre (id, name) VALUES (1009, "Piano Rock");
INSERT INTO Genre (id, name) VALUES (1010, "Piedmont Blues");
INSERT INTO Genre (id, name) VALUES (1011, "Pipe Band");
INSERT INTO Genre (id, name) VALUES (1012, "Poetry");
INSERT INTO Genre (id, name) VALUES (1013, "Polish Hip Hop");
INSERT INTO Genre (id, name) VALUES (1014, "Polish Indie");
INSERT INTO Genre (id, name) VALUES (1015, "Polish Jazz");
INSERT INTO Genre (id, name) VALUES (1016, "Polish Pop");
INSERT INTO Genre (id, name) VALUES (1017, "Polish Punk");
INSERT INTO Genre (id, name) VALUES (1018, "Polish Reggae");
INSERT INTO Genre (id, name) VALUES (1019, "Polka");
INSERT INTO Genre (id, name) VALUES (1020, "Polynesian Pop");
INSERT INTO Genre (id, name) VALUES (1021, "Polyphony");
INSERT INTO Genre (id, name) VALUES (1022, "Pop");
INSERT INTO Genre (id, name) VALUES (1023, "Pop Christmas");
INSERT INTO Genre (id, name) VALUES (1024, "Pop Emo");
INSERT INTO Genre (id, name) VALUES (1025, "Pop House");
INSERT INTO Genre (id, name) VALUES (1026, "Pop Punk");
INSERT INTO Genre (id, name) VALUES (1027, "Pop Rap");
INSERT INTO Genre (id, name) VALUES (1028, "Pop Rock");
INSERT INTO Genre (id, name) VALUES (1029, "Popgaze");
INSERT INTO Genre (id, name) VALUES (1030, "Porro");
INSERT INTO Genre (id, name) VALUES (1031, "Portland Indie");
INSERT INTO Genre (id, name) VALUES (1032, "Portuguese Pop");
INSERT INTO Genre (id, name) VALUES (1033, "Portuguese Rock");
INSERT INTO Genre (id, name) VALUES (1034, "Post Rock");
INSERT INTO Genre (id, name) VALUES (1035, "Post-disco");
INSERT INTO Genre (id, name) VALUES (1036, "Post-disco Soul");
INSERT INTO Genre (id, name) VALUES (1037, "Post-grunge");
INSERT INTO Genre (id, name) VALUES (1038, "Post-hardcore");
INSERT INTO Genre (id, name) VALUES (1039, "Post-metal");
INSERT INTO Genre (id, name) VALUES (1040, "Post-post-hardcore");
INSERT INTO Genre (id, name) VALUES (1041, "Post-punk");
INSERT INTO Genre (id, name) VALUES (1042, "Power Blues-rock");
INSERT INTO Genre (id, name) VALUES (1043, "Power Electronics");
INSERT INTO Genre (id, name) VALUES (1044, "Power Metal");
INSERT INTO Genre (id, name) VALUES (1045, "Power Noise");
INSERT INTO Genre (id, name) VALUES (1046, "Power Pop");
INSERT INTO Genre (id, name) VALUES (1047, "Power Violence");
INSERT INTO Genre (id, name) VALUES (1048, "Power-pop Punk");
INSERT INTO Genre (id, name) VALUES (1049, "Praise");
INSERT INTO Genre (id, name) VALUES (1050, "Progressive Alternative");
INSERT INTO Genre (id, name) VALUES (1051, "Progressive Bluegrass");
INSERT INTO Genre (id, name) VALUES (1052, "Progressive Electro House");
INSERT INTO Genre (id, name) VALUES (1053, "Progressive House");
INSERT INTO Genre (id, name) VALUES (1054, "Progressive Metal");
INSERT INTO Genre (id, name) VALUES (1055, "Progressive Psytrance");
INSERT INTO Genre (id, name) VALUES (1056, "Progressive Rock");
INSERT INTO Genre (id, name) VALUES (1057, "Progressive Trance");
INSERT INTO Genre (id, name) VALUES (1058, "Progressive Trance House");
INSERT INTO Genre (id, name) VALUES (1059, "Progressive Uplifting Trance");
INSERT INTO Genre (id, name) VALUES (1060, "Protopunk");
INSERT INTO Genre (id, name) VALUES (1061, "Psych Gaze");
INSERT INTO Genre (id, name) VALUES (1062, "Psychedelic Blues-rock");
INSERT INTO Genre (id, name) VALUES (1063, "Psychedelic Rock");
INSERT INTO Genre (id, name) VALUES (1064, "Psychedelic Trance");
INSERT INTO Genre (id, name) VALUES (1065, "Psychill");
INSERT INTO Genre (id, name) VALUES (1066, "Psychobilly");
INSERT INTO Genre (id, name) VALUES (1067, "Pub Rock");
INSERT INTO Genre (id, name) VALUES (1068, "Puerto Rican Rock");
INSERT INTO Genre (id, name) VALUES (1069, "Punjabi");
INSERT INTO Genre (id, name) VALUES (1070, "Punk");
INSERT INTO Genre (id, name) VALUES (1071, "Punk Blues");
INSERT INTO Genre (id, name) VALUES (1072, "Punk Christmas");
INSERT INTO Genre (id, name) VALUES (1073, "Punk Ska");
INSERT INTO Genre (id, name) VALUES (1074, "Qawwali");
INSERT INTO Genre (id, name) VALUES (1075, "Quebecois");
INSERT INTO Genre (id, name) VALUES (1076, "Quiet Storm");
INSERT INTO Genre (id, name) VALUES (1077, "R&b");
INSERT INTO Genre (id, name) VALUES (1078, "Ragga Jungle");
INSERT INTO Genre (id, name) VALUES (1079, "Ragtime");
INSERT INTO Genre (id, name) VALUES (1080, "Rai");
INSERT INTO Genre (id, name) VALUES (1081, "Ranchera");
INSERT INTO Genre (id, name) VALUES (1082, "Rap");
INSERT INTO Genre (id, name) VALUES (1083, "Rap Metal");
INSERT INTO Genre (id, name) VALUES (1084, "Rap Metalcore");
INSERT INTO Genre (id, name) VALUES (1085, "Rap Rock");
INSERT INTO Genre (id, name) VALUES (1086, "Raw Black Metal");
INSERT INTO Genre (id, name) VALUES (1087, "Re:techno");
INSERT INTO Genre (id, name) VALUES (1088, "Reading");
INSERT INTO Genre (id, name) VALUES (1089, "Rebetiko");
INSERT INTO Genre (id, name) VALUES (1090, "Reggae");
INSERT INTO Genre (id, name) VALUES (1091, "Reggae Fusion");
INSERT INTO Genre (id, name) VALUES (1092, "Reggae Rock");
INSERT INTO Genre (id, name) VALUES (1093, "Reggaeton");
INSERT INTO Genre (id, name) VALUES (1094, "Regional Mexican");
INSERT INTO Genre (id, name) VALUES (1095, "Relaxative");
INSERT INTO Genre (id, name) VALUES (1096, "Remix");
INSERT INTO Genre (id, name) VALUES (1097, "Renaissance");
INSERT INTO Genre (id, name) VALUES (1098, "Retro Electro");
INSERT INTO Genre (id, name) VALUES (1099, "Retro Metal");
INSERT INTO Genre (id, name) VALUES (1100, "Rhythm And Boogie");
INSERT INTO Genre (id, name) VALUES (1101, "Riddim");
INSERT INTO Genre (id, name) VALUES (1102, "Rio De La Plata");
INSERT INTO Genre (id, name) VALUES (1103, "Riot Grrrl");
INSERT INTO Genre (id, name) VALUES (1104, "Rock");
INSERT INTO Genre (id, name) VALUES (1105, "Rock Catala");
INSERT INTO Genre (id, name) VALUES (1106, "Rock En Espanol");
INSERT INTO Genre (id, name) VALUES (1107, "Rock Gaucho");
INSERT INTO Genre (id, name) VALUES (1108, "Rock Noise");
INSERT INTO Genre (id, name) VALUES (1109, "Rock Steady");
INSERT INTO Genre (id, name) VALUES (1110, "Rock-and-roll");
INSERT INTO Genre (id, name) VALUES (1111, "Rockabilly");
INSERT INTO Genre (id, name) VALUES (1112, "Romanian Pop");
INSERT INTO Genre (id, name) VALUES (1113, "Romanian Rock");
INSERT INTO Genre (id, name) VALUES (1114, "Romantic");
INSERT INTO Genre (id, name) VALUES (1115, "Roots Reggae");
INSERT INTO Genre (id, name) VALUES (1116, "Roots Rock");
INSERT INTO Genre (id, name) VALUES (1117, "Rumba");
INSERT INTO Genre (id, name) VALUES (1118, "Russian Alternative");
INSERT INTO Genre (id, name) VALUES (1119, "Russian Hip Hop");
INSERT INTO Genre (id, name) VALUES (1120, "Russian Pop");
INSERT INTO Genre (id, name) VALUES (1121, "Russian Punk");
INSERT INTO Genre (id, name) VALUES (1122, "Russian Rock");
INSERT INTO Genre (id, name) VALUES (1123, "Rva Indie");
INSERT INTO Genre (id, name) VALUES (1124, "Salsa");
INSERT INTO Genre (id, name) VALUES (1125, "Salsa International");
INSERT INTO Genre (id, name) VALUES (1126, "Samba");
INSERT INTO Genre (id, name) VALUES (1127, "Saxophone");
INSERT INTO Genre (id, name) VALUES (1128, "Schlager");
INSERT INTO Genre (id, name) VALUES (1129, "Schranz");
INSERT INTO Genre (id, name) VALUES (1130, "Scorecore");
INSERT INTO Genre (id, name) VALUES (1131, "Scottish Rock");
INSERT INTO Genre (id, name) VALUES (1132, "Scratch");
INSERT INTO Genre (id, name) VALUES (1133, "Screamo");
INSERT INTO Genre (id, name) VALUES (1134, "Screamo Punk");
INSERT INTO Genre (id, name) VALUES (1135, "Screamocore");
INSERT INTO Genre (id, name) VALUES (1136, "Seattle Indie");
INSERT INTO Genre (id, name) VALUES (1137, "Sega");
INSERT INTO Genre (id, name) VALUES (1138, "Serialism");
INSERT INTO Genre (id, name) VALUES (1139, "Sertanejo");
INSERT INTO Genre (id, name) VALUES (1140, "Sertanejo Tradicional");
INSERT INTO Genre (id, name) VALUES (1141, "Sertanejo Universitario");
INSERT INTO Genre (id, name) VALUES (1142, "Sevdah");
INSERT INTO Genre (id, name) VALUES (1143, "Shanty");
INSERT INTO Genre (id, name) VALUES (1144, "Sheffield Indie");
INSERT INTO Genre (id, name) VALUES (1145, "Shibuya-kei");
INSERT INTO Genre (id, name) VALUES (1146, "Shimmer Pop");
INSERT INTO Genre (id, name) VALUES (1147, "Shimmer Psych");
INSERT INTO Genre (id, name) VALUES (1148, "Shiver Pop");
INSERT INTO Genre (id, name) VALUES (1149, "Shoegaze");
INSERT INTO Genre (id, name) VALUES (1150, "Show Tunes");
INSERT INTO Genre (id, name) VALUES (1151, "Singaporean Pop");
INSERT INTO Genre (id, name) VALUES (1152, "Singer-songwriter");
INSERT INTO Genre (id, name) VALUES (1153, "Sinhala");
INSERT INTO Genre (id, name) VALUES (1154, "Ska");
INSERT INTO Genre (id, name) VALUES (1155, "Ska Punk");
INSERT INTO Genre (id, name) VALUES (1156, "Ska Revival");
INSERT INTO Genre (id, name) VALUES (1157, "Skate Punk");
INSERT INTO Genre (id, name) VALUES (1158, "Skiffle");
INSERT INTO Genre (id, name) VALUES (1159, "Skinhead Oi");
INSERT INTO Genre (id, name) VALUES (1160, "Skinhead Reggae");
INSERT INTO Genre (id, name) VALUES (1161, "Skweee");
INSERT INTO Genre (id, name) VALUES (1162, "Slam Death Metal");
INSERT INTO Genre (id, name) VALUES (1163, "Slash Punk");
INSERT INTO Genre (id, name) VALUES (1164, "Slc Indie");
INSERT INTO Genre (id, name) VALUES (1165, "Sleaze Rock");
INSERT INTO Genre (id, name) VALUES (1166, "Sleep");
INSERT INTO Genre (id, name) VALUES (1167, "Slovak Hip Hop");
INSERT INTO Genre (id, name) VALUES (1168, "Slovak Pop");
INSERT INTO Genre (id, name) VALUES (1169, "Slovenian Rock");
INSERT INTO Genre (id, name) VALUES (1170, "Slow Core");
INSERT INTO Genre (id, name) VALUES (1171, "Sludge Metal");
INSERT INTO Genre (id, name) VALUES (1172, "Smooth Jazz");
INSERT INTO Genre (id, name) VALUES (1173, "Smooth Urban R&b");
INSERT INTO Genre (id, name) VALUES (1174, "Soca");
INSERT INTO Genre (id, name) VALUES (1175, "Soda Pop");
INSERT INTO Genre (id, name) VALUES (1176, "Soft Rock");
INSERT INTO Genre (id, name) VALUES (1177, "Solipsynthm");
INSERT INTO Genre (id, name) VALUES (1178, "Soukous");
INSERT INTO Genre (id, name) VALUES (1179, "Soul");
INSERT INTO Genre (id, name) VALUES (1180, "Soul Blues");
INSERT INTO Genre (id, name) VALUES (1181, "Soul Christmas");
INSERT INTO Genre (id, name) VALUES (1182, "Soul Flow");
INSERT INTO Genre (id, name) VALUES (1183, "Soul Jazz");
INSERT INTO Genre (id, name) VALUES (1184, "Soundtrack");
INSERT INTO Genre (id, name) VALUES (1185, "South African Jazz");
INSERT INTO Genre (id, name) VALUES (1186, "Southern Gospel");
INSERT INTO Genre (id, name) VALUES (1187, "Southern Hip Hop");
INSERT INTO Genre (id, name) VALUES (1188, "Southern Rock");
INSERT INTO Genre (id, name) VALUES (1189, "Southern Soul");
INSERT INTO Genre (id, name) VALUES (1190, "Southern Soul Blues");
INSERT INTO Genre (id, name) VALUES (1191, "Space Rock");
INSERT INTO Genre (id, name) VALUES (1192, "Spanish Classical");
INSERT INTO Genre (id, name) VALUES (1193, "Spanish Folk");
INSERT INTO Genre (id, name) VALUES (1194, "Spanish Hip Hop");
INSERT INTO Genre (id, name) VALUES (1195, "Spanish Indie Pop");
INSERT INTO Genre (id, name) VALUES (1196, "Spanish Indie Rock");
INSERT INTO Genre (id, name) VALUES (1197, "Spanish Invasion");
INSERT INTO Genre (id, name) VALUES (1198, "Spanish New Wave");
INSERT INTO Genre (id, name) VALUES (1199, "Spanish Pop");
INSERT INTO Genre (id, name) VALUES (1200, "Spanish Pop Rock");
INSERT INTO Genre (id, name) VALUES (1201, "Spanish Punk");
INSERT INTO Genre (id, name) VALUES (1202, "Spanish Reggae");
INSERT INTO Genre (id, name) VALUES (1203, "Speed Garage");
INSERT INTO Genre (id, name) VALUES (1204, "Speed Metal");
INSERT INTO Genre (id, name) VALUES (1205, "Speedcore");
INSERT INTO Genre (id, name) VALUES (1206, "Spoken Word");
INSERT INTO Genre (id, name) VALUES (1207, "Spytrack");
INSERT INTO Genre (id, name) VALUES (1208, "Steampunk");
INSERT INTO Genre (id, name) VALUES (1209, "Steelpan");
INSERT INTO Genre (id, name) VALUES (1210, "Stl Indie");
INSERT INTO Genre (id, name) VALUES (1211, "Stomp And Flutter");
INSERT INTO Genre (id, name) VALUES (1212, "Stomp And Holler");
INSERT INTO Genre (id, name) VALUES (1213, "Stomp And Whittle");
INSERT INTO Genre (id, name) VALUES (1214, "Stomp Pop");
INSERT INTO Genre (id, name) VALUES (1215, "Stoner Metal");
INSERT INTO Genre (id, name) VALUES (1216, "Stoner Rock");
INSERT INTO Genre (id, name) VALUES (1217, "Straight Edge");
INSERT INTO Genre (id, name) VALUES (1218, "Street Punk");
INSERT INTO Genre (id, name) VALUES (1219, "Stride");
INSERT INTO Genre (id, name) VALUES (1220, "String Band");
INSERT INTO Genre (id, name) VALUES (1221, "String Folk");
INSERT INTO Genre (id, name) VALUES (1222, "String Quartet");
INSERT INTO Genre (id, name) VALUES (1223, "Substep");
INSERT INTO Genre (id, name) VALUES (1224, "Sunset Lounge");
INSERT INTO Genre (id, name) VALUES (1225, "Suomi Rock");
INSERT INTO Genre (id, name) VALUES (1226, "Surf Music");
INSERT INTO Genre (id, name) VALUES (1227, "Swamp Blues");
INSERT INTO Genre (id, name) VALUES (1228, "Swamp Pop");
INSERT INTO Genre (id, name) VALUES (1229, "Swedish Alternative Rock");
INSERT INTO Genre (id, name) VALUES (1230, "Swedish Hard Rock");
INSERT INTO Genre (id, name) VALUES (1231, "Swedish Hip Hop");
INSERT INTO Genre (id, name) VALUES (1232, "Swedish Indie Pop");
INSERT INTO Genre (id, name) VALUES (1233, "Swedish Indie Rock");
INSERT INTO Genre (id, name) VALUES (1234, "Swedish Jazz");
INSERT INTO Genre (id, name) VALUES (1235, "Swedish Metal");
INSERT INTO Genre (id, name) VALUES (1236, "Swedish Pop");
INSERT INTO Genre (id, name) VALUES (1237, "Swedish Pop Punk");
INSERT INTO Genre (id, name) VALUES (1238, "Swedish Prog");
INSERT INTO Genre (id, name) VALUES (1239, "Swedish Punk");
INSERT INTO Genre (id, name) VALUES (1240, "Swedish Reggae");
INSERT INTO Genre (id, name) VALUES (1241, "Swedish Soft Pop");
INSERT INTO Genre (id, name) VALUES (1242, "Swedish Synthpop");
INSERT INTO Genre (id, name) VALUES (1243, "Swing");
INSERT INTO Genre (id, name) VALUES (1244, "Swirl Psych");
INSERT INTO Genre (id, name) VALUES (1245, "Swiss Folk");
INSERT INTO Genre (id, name) VALUES (1246, "Swiss Hip Hop");
INSERT INTO Genre (id, name) VALUES (1247, "Swiss Rock");
INSERT INTO Genre (id, name) VALUES (1248, "Symphonic Black Metal");
INSERT INTO Genre (id, name) VALUES (1249, "Symphonic Metal");
INSERT INTO Genre (id, name) VALUES (1250, "Symphonic Rock");
INSERT INTO Genre (id, name) VALUES (1251, "Synthpop");
INSERT INTO Genre (id, name) VALUES (1252, "Taiwanese Pop");
INSERT INTO Genre (id, name) VALUES (1253, "Talent Show");
INSERT INTO Genre (id, name) VALUES (1254, "Tango");
INSERT INTO Genre (id, name) VALUES (1255, "Tech House");
INSERT INTO Genre (id, name) VALUES (1256, "Technical Brutal Death Metal");
INSERT INTO Genre (id, name) VALUES (1257, "Technical Death Metal");
INSERT INTO Genre (id, name) VALUES (1258, "Techno");
INSERT INTO Genre (id, name) VALUES (1259, "Teen Pop");
INSERT INTO Genre (id, name) VALUES (1260, "Tejano");
INSERT INTO Genre (id, name) VALUES (1261, "Tekno");
INSERT INTO Genre (id, name) VALUES (1262, "Terrorcore");
INSERT INTO Genre (id, name) VALUES (1263, "Texas Blues");
INSERT INTO Genre (id, name) VALUES (1264, "Texas Country");
INSERT INTO Genre (id, name) VALUES (1265, "Thai Indie");
INSERT INTO Genre (id, name) VALUES (1266, "Thai Pop");
INSERT INTO Genre (id, name) VALUES (1267, "Thrash Core");
INSERT INTO Genre (id, name) VALUES (1268, "Thrash Metal");
INSERT INTO Genre (id, name) VALUES (1269, "Thrash-groove Metal");
INSERT INTO Genre (id, name) VALUES (1270, "Throat Singing");
INSERT INTO Genre (id, name) VALUES (1271, "Tibetan");
INSERT INTO Genre (id, name) VALUES (1272, "Tico");
INSERT INTO Genre (id, name) VALUES (1273, "Timba");
INSERT INTO Genre (id, name) VALUES (1274, "Tin Pan Alley");
INSERT INTO Genre (id, name) VALUES (1275, "Traditional Blues");
INSERT INTO Genre (id, name) VALUES (1276, "Traditional British Folk");
INSERT INTO Genre (id, name) VALUES (1277, "Traditional Country");
INSERT INTO Genre (id, name) VALUES (1278, "Traditional Folk");
INSERT INTO Genre (id, name) VALUES (1279, "Traditional Funk");
INSERT INTO Genre (id, name) VALUES (1280, "Traditional Irish Folk");
INSERT INTO Genre (id, name) VALUES (1281, "Traditional Reggae");
INSERT INTO Genre (id, name) VALUES (1282, "Traditional Rock 'N Roll");
INSERT INTO Genre (id, name) VALUES (1283, "Traditional Rockabilly");
INSERT INTO Genre (id, name) VALUES (1284, "Traditional Scottish Folk");
INSERT INTO Genre (id, name) VALUES (1285, "Traditional Ska");
INSERT INTO Genre (id, name) VALUES (1286, "Traditional Soul");
INSERT INTO Genre (id, name) VALUES (1287, "Traditional Swing");
INSERT INTO Genre (id, name) VALUES (1288, "Trance");
INSERT INTO Genre (id, name) VALUES (1289, "Trance Hop");
INSERT INTO Genre (id, name) VALUES (1290, "Trap Music");
INSERT INTO Genre (id, name) VALUES (1291, "Trapstep");
INSERT INTO Genre (id, name) VALUES (1292, "Trash Rock");
INSERT INTO Genre (id, name) VALUES (1293, "Triangle Indie");
INSERT INTO Genre (id, name) VALUES (1294, "Tribal House");
INSERT INTO Genre (id, name) VALUES (1295, "Tribute");
INSERT INTO Genre (id, name) VALUES (1296, "Trip Hop");
INSERT INTO Genre (id, name) VALUES (1297, "Tropical");
INSERT INTO Genre (id, name) VALUES (1298, "Trova");
INSERT INTO Genre (id, name) VALUES (1299, "Turbo Folk");
INSERT INTO Genre (id, name) VALUES (1300, "Turkish Alternative");
INSERT INTO Genre (id, name) VALUES (1301, "Turkish Classical");
INSERT INTO Genre (id, name) VALUES (1302, "Turkish Folk");
INSERT INTO Genre (id, name) VALUES (1303, "Turkish Hip Hop");
INSERT INTO Genre (id, name) VALUES (1304, "Turkish Jazz");
INSERT INTO Genre (id, name) VALUES (1305, "Turkish Pop");
INSERT INTO Genre (id, name) VALUES (1306, "Turkish Rock");
INSERT INTO Genre (id, name) VALUES (1307, "Turntablism");
INSERT INTO Genre (id, name) VALUES (1308, "Twee Indie Pop");
INSERT INTO Genre (id, name) VALUES (1309, "Twee Pop");
INSERT INTO Genre (id, name) VALUES (1310, "Twin Cities Indie");
INSERT INTO Genre (id, name) VALUES (1311, "Tzadik");
INSERT INTO Genre (id, name) VALUES (1312, "Uk Dub");
INSERT INTO Genre (id, name) VALUES (1313, "Uk Garage");
INSERT INTO Genre (id, name) VALUES (1314, "Uk Hip Hop");
INSERT INTO Genre (id, name) VALUES (1315, "Uk Post-punk");
INSERT INTO Genre (id, name) VALUES (1316, "Ukrainian Rock");
INSERT INTO Genre (id, name) VALUES (1317, "Ukulele");
INSERT INTO Genre (id, name) VALUES (1318, "Unblack Metal");
INSERT INTO Genre (id, name) VALUES (1319, "Underground Hip Hop");
INSERT INTO Genre (id, name) VALUES (1320, "Underground Latin Hip Hop");
INSERT INTO Genre (id, name) VALUES (1321, "Underground Pop Rap");
INSERT INTO Genre (id, name) VALUES (1322, "Underground Power Pop");
INSERT INTO Genre (id, name) VALUES (1323, "Underground Rap");
INSERT INTO Genre (id, name) VALUES (1324, "Uplifting Trance");
INSERT INTO Genre (id, name) VALUES (1325, "Urban Contemporary");
INSERT INTO Genre (id, name) VALUES (1326, "Vallenato");
INSERT INTO Genre (id, name) VALUES (1327, "Vancouver Indie");
INSERT INTO Genre (id, name) VALUES (1328, "Vapor House");
INSERT INTO Genre (id, name) VALUES (1329, "Vaporwave");
INSERT INTO Genre (id, name) VALUES (1330, "Vegan Straight Edge");
INSERT INTO Genre (id, name) VALUES (1331, "Vegas Indie");
INSERT INTO Genre (id, name) VALUES (1332, "Velha Guarda");
INSERT INTO Genre (id, name) VALUES (1333, "Venezuelan Rock");
INSERT INTO Genre (id, name) VALUES (1334, "Video Game Music");
INSERT INTO Genre (id, name) VALUES (1335, "Vienna Indie");
INSERT INTO Genre (id, name) VALUES (1336, "Vietnamese Pop");
INSERT INTO Genre (id, name) VALUES (1337, "Viking Metal");
INSERT INTO Genre (id, name) VALUES (1338, "Vintage Chanson");
INSERT INTO Genre (id, name) VALUES (1339, "Vintage Country Folk");
INSERT INTO Genre (id, name) VALUES (1340, "Vintage Gospel");
INSERT INTO Genre (id, name) VALUES (1341, "Vintage Jazz");
INSERT INTO Genre (id, name) VALUES (1342, "Vintage Reggae");
INSERT INTO Genre (id, name) VALUES (1343, "Vintage Rockabilly");
INSERT INTO Genre (id, name) VALUES (1344, "Vintage Schlager");
INSERT INTO Genre (id, name) VALUES (1345, "Vintage Swedish Pop");
INSERT INTO Genre (id, name) VALUES (1346, "Vintage Swing");
INSERT INTO Genre (id, name) VALUES (1347, "Vintage Swoon");
INSERT INTO Genre (id, name) VALUES (1348, "Vintage Tango");
INSERT INTO Genre (id, name) VALUES (1349, "Vintage Western");
INSERT INTO Genre (id, name) VALUES (1350, "Violin");
INSERT INTO Genre (id, name) VALUES (1351, "Viral Pop");
INSERT INTO Genre (id, name) VALUES (1352, "Visual Kei");
INSERT INTO Genre (id, name) VALUES (1353, "Vocal House");
INSERT INTO Genre (id, name) VALUES (1354, "Vocal Jazz");
INSERT INTO Genre (id, name) VALUES (1355, "Vocaloid");
INSERT INTO Genre (id, name) VALUES (1356, "Volksmusik");
INSERT INTO Genre (id, name) VALUES (1357, "Warm Drone");
INSERT INTO Genre (id, name) VALUES (1358, "Welsh Rock");
INSERT INTO Genre (id, name) VALUES (1359, "West African Jazz");
INSERT INTO Genre (id, name) VALUES (1360, "West Coast Rap");
INSERT INTO Genre (id, name) VALUES (1361, "Western Swing");
INSERT INTO Genre (id, name) VALUES (1362, "Wind Ensemble");
INSERT INTO Genre (id, name) VALUES (1363, "Witch House");
INSERT INTO Genre (id, name) VALUES (1364, "Wonky");
INSERT INTO Genre (id, name) VALUES (1365, "Workout");
INSERT INTO Genre (id, name) VALUES (1366, "World");
INSERT INTO Genre (id, name) VALUES (1367, "World Chill");
INSERT INTO Genre (id, name) VALUES (1368, "World Christmas");
INSERT INTO Genre (id, name) VALUES (1369, "World Fusion");
INSERT INTO Genre (id, name) VALUES (1370, "Worship");
INSERT INTO Genre (id, name) VALUES (1371, "Wrestling");
INSERT INTO Genre (id, name) VALUES (1372, "Wrock");
INSERT INTO Genre (id, name) VALUES (1373, "Ye Ye");
INSERT INTO Genre (id, name) VALUES (1374, "Yoik");
INSERT INTO Genre (id, name) VALUES (1375, "Yugoslav Rock");
INSERT INTO Genre (id, name) VALUES (1376, "Zeuhl");
INSERT INTO Genre (id, name) VALUES (1377, "Zillertal");
INSERT INTO Genre (id, name) VALUES (1378, "Zim");
INSERT INTO Genre (id, name) VALUES (1379, "Zolo");
INSERT INTO Genre (id, name) VALUES (1380, "Zouglou");
INSERT INTO Genre (id, name) VALUES (1381, "Zouk");
INSERT INTO Genre (id, name) VALUES (1382, "Zydeco");
